/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CounterItem: typeof import('./src/components/itemDetails/CounterItem.vue')['default']
    CoverOverlay: typeof import('./src/components/common/CoverOverlay.vue')['default']
    CustomDataListTable: typeof import('./src/components/table/CustomDataListTable.vue')['default']
    CustomInput: typeof import('./src/components/form/CustomInput.vue')['default']
    CustomModal: typeof import('./src/components/common/CustomModal.vue')['default']
    CustomSelect: typeof import('./src/components/form/CustomSelect.vue')['default']
    DashboardLayout: typeof import('./src/components/layout/DashboardLayout.vue')['default']
    Datepicker: typeof import('./src/components/common/Datepicker.vue')['default']
    DropdownFilterbar: typeof import('./src/components/common/DropdownFilterbar.vue')['default']
    DynamicFormContainer: typeof import('./src/components/form/DynamicFormContainer.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElSelectV2: typeof import('element-plus/es')['ElSelectV2']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    FileUploadBlock: typeof import('./src/components/form/uploadBlock/FileUploadBlock.vue')['default']
    FileUploadBlockItem: typeof import('./src/components/form/uploadBlock/FileUploadBlockItem.vue')['default']
    Filterbar: typeof import('./src/components/common/Filterbar.vue')['default']
    ForgotPasswordForm: typeof import('./src/components/pages/ForgotPasswordForm.vue')['default']
    GridItemCardHeader: typeof import('./src/components/gridTable/GridItemCardHeader.vue')['default']
    ImagePreviewModal: typeof import('./src/components/common/ImagePreviewModal.vue')['default']
    InfoItem: typeof import('./src/components/itemDetails/InfoItem.vue')['default']
    ItemsGridContainer: typeof import('./src/components/gridTable/ItemsGridContainer.vue')['default']
    Login: typeof import('./src/components/pages/Login.vue')['default']
    LoginWrapper: typeof import('./src/components/pages/LoginWrapper.vue')['default']
    NewPasswordForm: typeof import('./src/components/pages/NewPasswordForm.vue')['default']
    PageMockImg: typeof import('./src/components/common/PageMockImg.vue')['default']
    PaginationContainer: typeof import('./src/components/common/PaginationContainer.vue')['default']
    PasswordCheckList: typeof import('./src/components/pages/PasswordCheckList.vue')['default']
    RadioButtonsBlock: typeof import('./src/components/form/RadioButtonsBlock.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/common/SearchBar.vue')['default']
    Sidebar: typeof import('./src/components/layout/Sidebar/Sidebar.vue')['default']
    SidebarWithSubs: typeof import('./src/components/layout/Sidebar/SidebarWithSubs.vue')['default']
    SimpleSpinner: typeof import('./src/components/common/SimpleSpinner.vue')['default']
    TableAction: typeof import('./src/components/table/TableAction.vue')['default']
    TabsBar: typeof import('./src/components/common/TabsBar.vue')['default']
    TopNavbar: typeof import('./src/components/layout/TopNavbar.vue')['default']
    VueElementLoading: typeof import('./src/components/common/VueElementLoading.vue')['default']
    VueElementLoadingWrapper: typeof import('./src/components/common/VueElementLoadingWrapper.vue')['default']
  }
}
