/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CoverOverlay: typeof import('./src/components/common/CoverOverlay.vue')['default']
    CustomInput: typeof import('./src/components/form/CustomInput.vue')['default']
    CustomModal: typeof import('./src/components/common/CustomModal.vue')['default']
    DashboardLayout: typeof import('./src/components/layout/DashboardLayout.vue')['default']
    Datepicker: typeof import('./src/components/common/Datepicker.vue')['default']
    DynamicFormContainer: typeof import('./src/components/form/DynamicFormContainer.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElSelectV2: typeof import('element-plus/es')['ElSelectV2']
    ElSubmenu: typeof import('element-plus/es')['ElSubmenu']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTimeSelect: typeof import('element-plus/es')['ElTimeSelect']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    ForgotPasswordForm: typeof import('./src/components/pages/ForgotPasswordForm.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    ImagePreviewModal: typeof import('./src/components/common/ImagePreviewModal.vue')['default']
    Login: typeof import('./src/components/pages/Login.vue')['default']
    LoginWrapper: typeof import('./src/components/pages/LoginWrapper.vue')['default']
    NewPasswordForm: typeof import('./src/components/pages/NewPasswordForm.vue')['default']
    PasswordCheckList: typeof import('./src/components/pages/PasswordCheckList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/common/SearchBar.vue')['default']
    Sidebar: typeof import('./src/components/layout/Sidebar/Sidebar.vue')['default']
    SidebarWithSubs: typeof import('./src/components/layout/Sidebar/SidebarWithSubs.vue')['default']
    SimpleSpinner: typeof import('./src/components/common/SimpleSpinner.vue')['default']
    TableAction: typeof import('./src/components/table/TableAction.vue')['default']
    TabsBar: typeof import('./src/components/common/TabsBar.vue')['default']
    TopNavbar: typeof import('./src/components/layout/TopNavbar.vue')['default']
    VueElementLoading: typeof import('./src/components/common/VueElementLoading.vue')['default']
    VueElementLoadingWrapper: typeof import('./src/components/common/VueElementLoadingWrapper.vue')['default']
  }
}
