// import { getDateRange } from '@/helpers';
import { USER_TYPES } from '@/constants/global';

export const rolesHasAccessTo = {
	'operate-plants': [
		USER_TYPES.SUPER_ADMIN,
		USER_TYPES.DISTRIBUTOR,
		USER_TYPES.PLANT_ADMIN
	],
	'operate-p-lines': [
		USER_TYPES.SUPER_ADMIN,
		USER_TYPES.DISTRIBUTOR,
		USER_TYPES.PLANT_ADMIN,
		USER_TYPES.PLANT_SUPERINTENDENT
	],
	'operate-machines': [
		USER_TYPES.SUPER_ADMIN,
		USER_TYPES.DISTRIBUTOR,
		USER_TYPES.PLANT_ADMIN,
		USER_TYPES.PLANT_SUPERINTENDENT
	],
	'operate-assets': [
		USER_TYPES.SUPER_ADMIN,
		USER_TYPES.DISTRIBUTOR,
		USER_TYPES.PLANT_ADMIN,
		USER_TYPES.PLANT_SUPERINTENDENT
	],
	'operate-equipments': [
		USER_TYPES.SUPER_ADMIN,
		USER_TYPES.DISTRIBUTOR,
		USER_TYPES.PLANT_ADMIN,
		USER_TYPES.PLANT_SUPERINTENDENT
	],
	'operate-acknowledge': [
		USER_TYPES.SUPER_ADMIN,
		USER_TYPES.DISTRIBUTOR,
		USER_TYPES.PLANT_USER,
		USER_TYPES.PLANT_ADMIN,
		USER_TYPES.PLANT_SUPERINTENDENT
	],
	're-baseline': [
		USER_TYPES.SUPER_ADMIN,
		USER_TYPES.DISTRIBUTOR,
		USER_TYPES.PLANT_SUPERINTENDENT,
		USER_TYPES.PLANT_ADMIN
	],
	'request-quote': [
		USER_TYPES.SUPER_ADMIN,
		USER_TYPES.DISTRIBUTOR,
		USER_TYPES.PLANT_SUPERINTENDENT,
		USER_TYPES.PLANT_ADMIN,
		USER_TYPES.PLANT_USER
	],
	'request-service': [
		USER_TYPES.SUPER_ADMIN,
		USER_TYPES.DISTRIBUTOR,
		USER_TYPES.PLANT_SUPERINTENDENT,
		USER_TYPES.PLANT_ADMIN,
		USER_TYPES.PLANT_USER
	],
	'create-vendors': [USER_TYPES.SUPER_ADMIN],
	'edit-equipment': [
		USER_TYPES.SUPER_ADMIN,
		USER_TYPES.DISTRIBUTOR,
		USER_TYPES.PLANT_ADMIN
	],
	'create-delete-sensor': [
		USER_TYPES.SUPER_ADMIN,
		USER_TYPES.DISTRIBUTOR,
		USER_TYPES.PLANT_ADMIN
	],
	'delete-logs': [
		USER_TYPES.SUPER_ADMIN,
		USER_TYPES.DISTRIBUTOR,
		USER_TYPES.PLANT_ADMIN
		// USER_TYPES.PLANT_SUPERINTENDENT,
	],
	'operate-proccesses': [
		USER_TYPES.SUPER_ADMIN,
		USER_TYPES.DISTRIBUTOR,
		// USER_TYPES.PLANT_ADMIN,
		// USER_TYPES.PLANT_USER,
		USER_TYPES.PLANT_SUPERINTENDENT
	],
	'create-logs': [
		USER_TYPES.SUPER_ADMIN,
		USER_TYPES.DISTRIBUTOR,
		USER_TYPES.PLANT_ADMIN,
		// USER_TYPES.PLANT_USER,
		USER_TYPES.PLANT_SUPERINTENDENT,
		USER_TYPES.OEE_PROCCESS
	],
	'edit-logs': [
		USER_TYPES.SUPER_ADMIN,
		USER_TYPES.DISTRIBUTOR,
		USER_TYPES.PLANT_ADMIN,
		USER_TYPES.PLANT_USER,
		USER_TYPES.PLANT_SUPERINTENDENT,
		USER_TYPES.OEE_PROCCESS
	],
	'thresholds': [
		USER_TYPES.SUPER_ADMIN,
		USER_TYPES.DISTRIBUTOR,
		USER_TYPES.PLANT_SUPERINTENDENT,
		USER_TYPES.PLANT_ADMIN
	],
	'gain_adjustment': [
		USER_TYPES.SUPER_ADMIN,
		USER_TYPES.DISTRIBUTOR,
		USER_TYPES.PLANT_SUPERINTENDENT,
		USER_TYPES.PLANT_ADMIN,
		USER_TYPES.OEE_PROCCESS
	],
	'operate-maintenace-work-orders': [
		USER_TYPES.SUPER_ADMIN,
		USER_TYPES.PLANT_SUPERINTENDENT,
		USER_TYPES.PLANT_ADMIN,
		USER_TYPES.PLANT_USER
	],
	'delete-maintenace-work-orders': [
		USER_TYPES.SUPER_ADMIN,
		USER_TYPES.PLANT_SUPERINTENDENT,
		USER_TYPES.PLANT_ADMIN
	],
	'complete-maintenace-work-orders': [
		USER_TYPES.SUPER_ADMIN,
		USER_TYPES.PLANT_SUPERINTENDENT,
		USER_TYPES.PLANT_ADMIN,
		USER_TYPES.PLANT_USER
	],
	'close-maintenace-work-orders': [USER_TYPES.SUPER_ADMIN, USER_TYPES.PLANT_ADMIN],
	'operate-maintenace-logs': [
		USER_TYPES.SUPER_ADMIN,
		USER_TYPES.PLANT_SUPERINTENDENT,
		USER_TYPES.PLANT_ADMIN,
		USER_TYPES.PLANT_USER
	],
	'operate-maintenace-requests': [USER_TYPES.SUPER_ADMIN, USER_TYPES.PLANT_USER],
	'edit-maintenace-requests': [
		USER_TYPES.SUPER_ADMIN,
		USER_TYPES.PLANT_USER,
		USER_TYPES.PLANT_ADMIN
	],
	'edit-meeting-trackers': [
		USER_TYPES.SUPER_ADMIN
		// USER_TYPES.PLANT_USER,
		// USER_TYPES.PLANT_ADMIN,
		// USER_TYPES.PLANT_SUPERINTENDENT,
	],
	'edit-rois': [
		USER_TYPES.SUPER_ADMIN,
		USER_TYPES.PLANT_USER,
		USER_TYPES.PLANT_ADMIN,
		USER_TYPES.PLANT_SUPERINTENDENT
	]
};
// export { rolesHasAccessTo };
