export const ENTITIES = Object.freeze({
	Applications: Object.freeze({
		key: 'applications',
		apiBase: '/applications',
		routeBase: '/applications',
		filtersStorageKey: 'applications_filters',
		itemsName: Object.freeze({
			one: 'Application',
			mult: 'Applications',
			instanceName: 'applications',
		}),
		permissions: Object.freeze({
			view: 'view_applications',
			create: 'create_applications',
			edit: 'edit_applications',
			delete: 'delete_applications',
		}),
	}),
	Assets: Object.freeze({
		key: 'assets',
		apiBase: '/assets',
		routeBase: '/assets',
		filtersStorageKey: 'assets_filters',
		itemsName: Object.freeze({
			one: 'Asset',
			mult: 'Assets',
			instanceName: 'assets',
		}),
	}),
	Brands: Object.freeze({
		key: 'brands',
		apiBase: '/equipments/brands',
		routeBase: '/brands',
		filtersStorageKey: 'brands_filters',
		itemsName: Object.freeze({
			one: 'Equipment_Brand',
			mult: 'Equipment_Brands',
			instanceName: 'brands',
		}),
		permissions: Object.freeze({
			view: 'view_brands',
			create: 'create_brands',
			edit: 'edit_brands',
			delete: 'delete_brands',
		}),
		menu: Object.freeze({
			label: 'Brands',
			icon: 'icon-brands',
			path: '/brands',
		}),
	}),
	BrandModels: Object.freeze({
		key: 'brand_models',
		apiBase: '/equipments/brands/models',
		routeBase: '/brand-models',
		filtersStorageKey: 'brand_models_filters',
		itemsName: Object.freeze({
			one: 'Part_Number',
			mult: 'Part_Numbers',
			instanceName: 'brand_models',
		}),
		permissions: Object.freeze({
			view: 'view_part_numbers',
			create: 'create_part_numbers',
			edit: 'edit_part_numbers',
			delete: 'delete_part_numbers',
		}),
		menu: Object.freeze({
			label: 'part_numbers',
			icon: 'icon-part-numbers2',
			path: '/brand-models',
		}),
	}),
	Companies: Object.freeze({
		key: 'companies',
		apiBase: '/companies',
		routeBase: '/companies',
		filtersStorageKey: 'companies_filters',
		itemsName: Object.freeze({
			one: 'Company',
			mult: 'Companies',
			instanceName: 'companies',
		}),
		permissions: Object.freeze({
			view: 'view_companies',
			create: 'create_companies',
			edit: 'edit_companies',
			delete: 'delete_companies',
		}),
	}),
	Controllers: Object.freeze({
		key: 'controllers',
		apiBase: '/controllers',
		routeBase: '/controllers',
		filtersStorageKey: 'controllers_filters',
		itemsName: Object.freeze({
			one: 'Controller',
			mult: 'Controllers',
			instanceName: 'controllers',
		}),
		permissions: Object.freeze({
			view: 'view_controllers',
			create: 'create_controllers',
			edit: 'edit_controllers',
			delete: 'delete_controllers',
		}),
	}),
	Distributors: Object.freeze({
		key: 'distributors',
		apiBase: '/distributors',
		routeBase: '/distributors',
		filtersStorageKey: 'distributors_filters',
		itemsName: Object.freeze({
			one: 'Distributor',
			mult: 'Distributors',
			instanceName: 'distributors',
		}),
		permissions: Object.freeze({
			view: 'view_distributors',
			create: 'create_distributors',
			edit: 'edit_distributors',
			delete: 'delete_distributors',
		}),
		menu: Object.freeze({
			label: 'Distributors',
			icon: 'icon-distributors',
			path: '/distributors',
		}),
	}),
	EquipmentTypesCategories: Object.freeze({
		key: 'equipment_types_categories',
		apiBase: '/equipments/types/options/categories',
		routeBase: '/equipment-types-categories',
		filtersStorageKey: 'equipment-types-categories_filters',
		itemsName: Object.freeze({
			one: 'Category',
			mult: 'Categories',
			group: 'Item_Types',
			instanceName: 'equipment_types',
		}),
		permissions: Object.freeze({
			view: 'view_equipment_types_categories',
			create: 'create_equipment_types_categories',
			edit: 'edit_equipment_types_categories',
			delete: 'delete_equipment_types_categories',
		}),
	}),
	EquipmentTypes: Object.freeze({
		key: 'equipment_types',
		apiBase: '/equipments/types',
		routeBase: '/equipment-types',
		filtersStorageKey: 'equipment_types_filters',
		itemsName: Object.freeze({
			one: 'Item_Type',
			mult: 'Item_Types',
			instanceName: 'equipment_types',
		}),
		permissions: Object.freeze({
			view: 'view_equipment_types',
			create: 'create_equipment_types',
			edit: 'edit_equipment_types',
			delete: 'delete_equipment_types',
		}),
	}),
	Equipments: Object.freeze({
		key: 'equipments',
		apiBase: '/equipments',
		routeBase: '/equipments',
		filtersStorageKey: 'equipments_filters',
		itemsName: Object.freeze({
			one: 'Item',
			mult: 'Items',
			instanceName: 'equipments',
		}),
	}),
	Library: Object.freeze({
		key: 'libraries',
		apiBase: '/libraries',
		routeBase: '/library',
		filtersStorageKey: 'libraries_filters',
		itemsName: Object.freeze({
			one: 'sidebar_menu.library',
			mult: 'libraries',
			instanceName: 'library',
		}),
		permissions: Object.freeze({
			view: 'view_library',
		}),
	}),
	Machines: Object.freeze({
		key: 'machines',
		apiBase: '/machines',
		routeBase: '/machines',
		filtersStorageKey: 'machines_filters',
		itemsName: Object.freeze({
			one: 'Machine',
			mult: 'Machines',
			instanceName: 'machines',
		}),
	}),
	MaintenanceCategories: Object.freeze({
		key: 'maintenance_categories',
		apiBase: '/maintenance/categories',
		routeBase: '/maintenance-categories',
		filtersStorageKey: 'maintenance_categories_filters',
		itemsName: Object.freeze({
			one: 'Work_Order_Type',
			mult: 'Work_Order_Types',
			instanceName: 'maintenance_categories',
		}),
		permissions: Object.freeze({
			view: 'view_work_order_type',
			create: 'create_work_order_type',
			edit: 'edit_work_order_type',
			delete: 'delete_work_order_type',
		}),
	}),
	MaintenanceLogs: Object.freeze({
		key: 'maintenance_logs',
		apiBase: '/maintenance',
		routeBase: '/maintenance/logs',
		filtersStorageKey: 'maintenance_logs_filters',
		itemsName: Object.freeze({
			one: 'Maintenance_Log',
			mult: 'Maintenance_Logs',
			instanceName: 'maintenance',
		}),
		permissions: Object.freeze({
			view: 'view_maintenance',
			create: 'create_maintenance',
			edit: 'edit_maintenance',
			delete: 'delete_maintenance',
		}),
	}),
	MeetingTrackers: Object.freeze({
		key: 'meeting_trackers',
		apiBase: '/plants/meeting-trackers',
		routeBase: '/success-dashboard/meeting-tracker',
		filtersStorageKey: 'meeting-trackers_filters',
		itemsName: Object.freeze({
			one: 'Meeting_Tracker',
			mult: 'Meeting_Trackers',
			instanceName: 'meeting_trackers',
		}),
		permissions: Object.freeze({
			view: 'view_customer_success',
			create: 'create_customer_success',
			edit: 'edit_customer_success',
			delete: 'delete_customer_success',
		}),
	}),
	RoiOnePagers: Object.freeze({
		key: 'roi_one_pagers',
		apiBase: '/plants/roi/one-pagers',
		routeBase: '/success-dashboard/roi-one-pager',
		filtersStorageKey: 'roi-one-pagers_filters',
		itemsName: Object.freeze({
			one: 'ROI_One_Pager',
			mult: 'ROI_One_Pagers',
			instanceName: 'roi_one_pagers',
		}),
		permissions: Object.freeze({
			view: 'view_customer_success',
			create: 'create_customer_success',
			edit: 'edit_customer_success',
			delete: 'delete_customer_success',
		}),
	}),
	WorkOrders: Object.freeze({
		key: 'work_orders',
		apiBase: '/maintenance',
		routeBase: '/maintenance/work-orders',
		filtersStorageKey: 'maintenance_wo_filters',
		itemsName: Object.freeze({
			one: 'Work_Order',
			mult: 'Work_Orders',
			instanceName: 'maintenance',
		}),
		permissions: Object.freeze({
			view: 'view_maintenance',
			create: 'create_maintenance',
			edit: 'edit_maintenance',
			delete: 'delete_maintenance',
		}),
	}),
	WorkOrderRequests: Object.freeze({
		key: 'work_order_requests',
		apiBase: '/maintenance/requests',
		routeBase: '/maintenance-requests',
		filtersStorageKey: 'maintenance_requests_filters',
		itemsName: Object.freeze({
			one: 'Work_Order_Request',
			mult: 'Work_Order_Requests',
			instanceName: 'maintenance',
		}),
		permissions: Object.freeze({
			view: 'view_work_order_requests',
			create: 'create_work_order_requests',
			edit: 'edit_work_order_requests',
			delete: 'delete_work_order_requests',
		}),
	}),
	Requisitions: Object.freeze({
		key: 'plant_requisitions',
		apiBase: '/plants/work-orders',
		routeBase: '/requisitions',
		filtersStorageKey: 'plant-requisitions_filters',
		itemsName: Object.freeze({
			one: 'Requisition',
			mult: 'Requisitions',
			instanceName: 'plant_requisitions',
		}),
		permissions: Object.freeze({
			view: 'view_requisitions',
			create: 'create_requisitions',
			edit: 'edit_requisitions',
			delete: 'delete_requisitions',
		}),
	}),
	Rfqs: Object.freeze({
		key: 'rfqs',
		apiBase: '/rfqs',
		routeBase: '/rfqs',
		filtersStorageKey: 'rfqs_filters',
		itemsName: Object.freeze({
			one: 'phrases.Request_for_quotation',
			mult: 'phrases.Request_for_quotations',
			instanceName: 'rfqs',
		}),
		permissions: Object.freeze({
			view: 'view_rfqs',
			create: 'create_rfqs',
			edit: 'edit_rfqs',
			delete: 'delete_rfqs',
		}),
	}),
	IndustrialServices: Object.freeze({
		key: 'industrial_services',
		apiBase: '/settings/industrial-services',
		routeBase: '/settings/industrial-services',
		filtersStorageKey: 'industrial_services_filters',
		itemsName: Object.freeze({
			one: 'Industrial_Service',
			mult: 'Industrial_Services',
			instanceName: 'industrial_services',
		}),
		permissions: Object.freeze({
			view: 'view_settings',
			create: 'create_settings',
			edit: 'edit_settings',
			delete: 'delete_settings',
		}),
	}),
	LubeTypes: Object.freeze({
		key: 'lube_types',
		apiBase: '/ultrasound/lubricant-types',
		routeBase: '/settings/lube-type',
		filtersStorageKey: 'lube_types_filters',
		itemsName: Object.freeze({
			one: 'Lube_Type',
			mult: 'Lube_Types',
			instanceName: 'lube_types',
		}),
		permissions: Object.freeze({
			view: 'view_settings',
			create: 'create_settings',
			edit: 'edit_settings',
			delete: 'delete_settings',
		}),
	}),
	Bearings: Object.freeze({
		key: 'bearings',
		apiBase: '/bearings',
		routeBase: '/settings/bearing',
		filtersStorageKey: 'bearings_filters',
		itemsName: Object.freeze({
			one: 'Bearing',
			mult: 'Bearings',
			instanceName: 'bearings',
		}),
		permissions: Object.freeze({
			view: 'view_settings',
			create: 'create_settings',
			edit: 'edit_settings',
			delete: 'delete_settings',
		}),
	}),
	BannerV2Subtypes: Object.freeze({
		key: 'banner_v2_subtypes',
		apiBase: '/sensors/banner-v2/subtypes',
		routeBase: '/settings/banner-v2-subtypes',
		filtersStorageKey: 'banner-v2-subtypes_filters',
		itemsName: Object.freeze({
			one: 'phrases.Banner_V2_subtype',
			mult: 'phrases.Banner_V2_subtypes',
			instanceName: 'banner_v2_subtypes',
		}),
		permissions: Object.freeze({
			view: 'view_settings',
			create: 'create_settings',
			edit: 'edit_settings',
			delete: 'delete_settings',
		}),
	}),
	EquipmentFaults: Object.freeze({
		key: 'equipment_faults',
		apiBase: '/equipments/faults',
		routeBase: '/settings/faults',
		filtersStorageKey: 'equipments_filters',
		itemsName: Object.freeze({
			one: 'Fault',
			mult: 'Faults',
			instanceName: 'equipments',
		}),
		permissions: Object.freeze({
			view: 'view_settings',
			create: 'create_settings',
			edit: 'edit_settings',
			delete: 'delete_settings',
		}),
	}),
	Parts: Object.freeze({
		key: 'parts',
		apiBase: '/plants/parts',
		routeBase: '/parts',
		filtersStorageKey: 'parts_filters',
		itemsName: Object.freeze({
			one: 'Part',
			mult: 'Parts',
			instanceName: 'parts',
		}),
		permissions: Object.freeze({
			view: 'view_misc_parts',
			create: 'create_misc_parts',
			edit: 'edit_misc_parts',
			delete: 'delete_misc_parts',
		}),
	}),
	Plants: Object.freeze({
		key: 'plants',
		apiBase: '/plants',
		routeBase: '/plants',
		filtersStorageKey: 'plants_filters',
		itemsName: Object.freeze({
			one: 'Plant',
			mult: 'Plants',
			instanceName: 'plants',
		}),
		permissions: Object.freeze({
			view: 'view_plants',
			create: 'create_plants',
			edit: 'edit_plants',
			delete: 'delete_plants',
		}),
	}),
	Locations: Object.freeze({
		key: 'locations',
		apiBase: '/locations',
		// routeBase: '/locations',
		// filtersStorageKey: 'locations_filters',
		itemsName: Object.freeze({
			one: 'Location',
			mult: 'Locations',
			instanceName: 'locations',
		}),
	}),
	PlantsVendors: Object.freeze({
		key: 'plants_vendors',
		apiBase: '/plants/vendors',
		routeBase: '/plants-vendors',
		filtersStorageKey: 'plants-vendors_filters',
		itemsName: Object.freeze({
			one: 'Vendor',
			mult: 'Vendors',
			instanceName: 'plants_vendors',
			englishPrefix: 'Plants ',
		}),
		permissions: Object.freeze({
			view: 'view_vendors',
			create: 'create_vendors',
			edit: 'edit_vendors',
			delete: 'delete_vendors',
		}),
	}),
	Processes: Object.freeze({
		key: 'processes',
		apiBase: '/plants/conveyor/processes',
		routeBase: '/processes',
		filtersStorageKey: 'processes_filters',
		itemsName: Object.freeze({
			one: 'Process',
			mult: 'Processes',
			instanceName: 'processes',
		}),
		permissions: Object.freeze({
			view: 'view_oee',
			create: 'create_oee',
			edit: 'edit_oee',
			delete: 'delete_oee',
		}),
	}),
	ProductionLines: Object.freeze({
		key: 'production_lines',
		apiBase: '/production-lines',
		routeBase: '/production-lines',
		filtersStorageKey: 'production_lines_filters',
		itemsName: Object.freeze({
			one: 'Production_Line',
			mult: 'Production_Lines',
			instanceName: 'production_lines',
		}),
	}),
	Teams: Object.freeze({
		key: 'teams',
		apiBase: '/team',
		routeBase: '/teams',
		filtersStorageKey: 'teams_filters',
		itemsName: Object.freeze({
			one: 'Team',
			mult: 'Teams',
			instanceName: 'teams',
		}),
		permissions: Object.freeze({
			view: 'view_users_teams',
			create: 'create_users_teams',
			edit: 'edit_users_teams',
			delete: 'delete_users_teams',
		}),
	}),
	Users: Object.freeze({
		key: 'users',
		apiBase: '/users',
		routeBase: '/users',
		filtersStorageKey: 'users_filters',
		itemsName: Object.freeze({
			one: 'User',
			mult: 'Users',
			instanceName: 'users',
		}),
		permissions: Object.freeze({
			view: 'view_users',
			create: 'create_users',
			edit: 'edit_users',
			delete: 'delete_users',
		}),
	}),
	UserRoles: Object.freeze({
		key: 'user_roles',
		apiBase: '/roles',
		routeBase: '/user-roles',
		filtersStorageKey: 'user-roles_filters',
		itemsName: Object.freeze({
			one: 'sidebar_menu.user_roles',
			mult: 'sidebar_menu.user_roles',
			instanceName: 'user_roles',
		}),
		permissions: Object.freeze({
			view: 'view_user_roles',
			create: 'create_user_roles',
			edit: 'edit_user_roles',
			delete: 'delete_user_roles',
		}),
	}),
	Sensors: Object.freeze({
		key: 'sensors',
		apiBase: '/sensors',
		routeBase: '/sensors',
		filtersStorageKey: 'sensors_filters',
		itemsName: Object.freeze({
			one: 'sensors',
			mult: 'sensors',
			instanceName: 'sensors',
		}),
		permissions: Object.freeze({
			view: 'view_sensors',
			create: 'create_sensors',
			edit: 'edit_sensors',
			delete: 'delete_sensors',
		}),
	}),
	StoreRooms: Object.freeze({
		key: 'store_rooms',
		apiBase: '/store-rooms',
		routeBase: '/store-rooms',
		filtersStorageKey: 'store_rooms_filters',
		itemsName: Object.freeze({
			one: 'StoreRoom',
			mult: 'StoreRooms',
			instanceName: 'store_rooms',
		}),
		permissions: Object.freeze({
			view: 'view_storerooms',
			create: 'create_storerooms',
			edit: 'edit_storerooms',
			delete: 'delete_storerooms',
		}),
		menu: Object.freeze({
			label: 'storerooms',
			path: '/store-rooms',
		}),
	}),
	TaskProcedures: Object.freeze({
		key: 'task_procedures',
		apiBase: '/plants/task-procedures',
		routeBase: '/task-procedures',
		filtersStorageKey: 'task-procedures_filters',
		itemsName: Object.freeze({
			one: 'Task_procedure',
			mult: 'Task_procedures',
			instanceName: 'task_procedures',
		}),
		permissions: Object.freeze({
			view: 'view_task_procedures',
			create: 'create_task_procedures',
			edit: 'edit_task_procedures',
			delete: 'delete_task_procedures',
		}),
		menu: Object.freeze({
			label: 'task_Procedures',
			icon: 'icon-task_procedures',
			path: '/task-procedures',
		}),
	}),
});
