export const ENTITIES = Object.freeze({
	Applications: Object.freeze({
		key: 'applications',
		apiBase: '/applications',
		routeBase: '/applications',
		filtersStorageKey: 'applications_filters',
		itemsName: Object.freeze({
			one: 'Application',
			mult: 'Applications',
			instanceName: 'applications',
		}),
		permissions: Object.freeze({
			view: 'view_applications',
			create: 'create_applications',
			edit: 'edit_applications',
			delete: 'delete_applications',
		}),
	}),
	Brands: Object.freeze({
		key: 'brands',
		apiBase: '/equipments/brands',
		routeBase: '/brands',
		filtersStorageKey: 'brands_filters',
		itemsName: Object.freeze({
			one: 'Equipment_Brand',
			mult: 'Equipment_Brands',
			instanceName: 'brands',
		}),
		permissions: Object.freeze({
			view: 'view_brands',
			create: 'create_brands',
			edit: 'edit_brands',
			delete: 'delete_brands',
		}),
		menu: Object.freeze({
			label: 'Brands',
			icon: 'icon-brands',
			path: '/brands',
		}),
	}),
	BrandModels: Object.freeze({
		key: 'brand_models',
		apiBase: '/equipments/brands/models',
		routeBase: '/brand-models',
		filtersStorageKey: 'brand_models_filters',
		itemsName: Object.freeze({
			one: 'Part_Number',
			mult: 'Part_Numbers',
			instanceName: 'brand_models',
		}),
		permissions: Object.freeze({
			view: 'view_part_numbers',
			create: 'create_part_numbers',
			edit: 'edit_part_numbers',
			delete: 'delete_part_numbers',
		}),
		menu: Object.freeze({
			label: 'part_numbers',
			icon: 'icon-part-numbers2',
			path: '/brand-models',
		}),
	}),
	Companies: Object.freeze({
		key: 'companies',
		apiBase: '/companies',
		routeBase: '/companies',
		filtersStorageKey: 'companies_filters',
		itemsName: Object.freeze({
			one: 'Company',
			mult: 'Companies',
			instanceName: 'companies',
		}),
		permissions: Object.freeze({
			view: 'view_companies',
			create: 'create_companies',
			edit: 'edit_companies',
			delete: 'delete_companies',
		}),
	}),
	Controllers: Object.freeze({
		key: 'controllers',
		apiBase: '/controllers',
		routeBase: '/controllers',
		filtersStorageKey: 'controllers_filters',
		itemsName: Object.freeze({
			one: 'Controller',
			mult: 'Controllers',
			instanceName: 'controllers',
		}),
		permissions: Object.freeze({
			view: 'view_controllers',
			create: 'create_controllers',
			edit: 'edit_controllers',
			delete: 'delete_controllers',
		}),
	}),
	EquipmentTypesCategories: Object.freeze({
		key: 'equipment_types_categories',
		apiBase: '/equipments/types/options/categories',
		routeBase: '/equipment-types-categories',
		filtersStorageKey: 'equipment-types-categories_filters',
		itemsName: Object.freeze({
			one: 'Category',
			mult: 'Categories',
			group: 'Item_Types',
			instanceName: 'equipment_types',
		}),
		permissions: Object.freeze({
			view: 'view_equipment_types_categories',
			create: 'create_equipment_types_categories',
			edit: 'edit_equipment_types_categories',
			delete: 'delete_equipment_types_categories',
		}),
	}),
	EquipmentTypes: Object.freeze({
		key: 'equipment_types',
		apiBase: '/equipments/types',
		routeBase: '/equipment-types',
		filtersStorageKey: 'equipment_types_filters',
		itemsName: Object.freeze({
			one: 'Item_Type',
			mult: 'Item_Types',
			instanceName: 'equipment_types',
		}),
		permissions: Object.freeze({
			view: 'view_equipment_types',
			create: 'create_equipment_types',
			edit: 'edit_equipment_types',
			delete: 'delete_equipment_types',
		}),
	}),
	Machines: Object.freeze({
		key: 'machines',
		apiBase: '/machines',
		routeBase: '/machines',
		filtersStorageKey: 'machines_filters',
		itemsName: Object.freeze({
			one: 'Machine',
			mult: 'Machines',
			instanceName: 'machines',
		}),
	}),
	MaintenanceCategories: Object.freeze({
		key: 'maintenance_categories',
		apiBase: '/maintenance/categories',
		routeBase: '/maintenance-categories',
		filtersStorageKey: 'maintenance_categories_filters',
		itemsName: Object.freeze({
			one: 'Work_Order_Type',
			mult: 'Work_Order_Types',
			instanceName: 'maintenance_categories',
		}),
		permissions: Object.freeze({
			view: 'view_work_order_type',
			create: 'create_work_order_type',
			edit: 'edit_work_order_type',
			delete: 'delete_work_order_type',
		}),
	}),
	IndustrialServices: Object.freeze({
		key: 'industrial_services',
		apiBase: '/settings/industrial-services',
		routeBase: '/settings/industrial-services',
		filtersStorageKey: 'industrial_services_filters',
		itemsName: Object.freeze({
			one: 'Industrial_Service',
			mult: 'Industrial_Services',
			instanceName: 'industrial_services',
		}),
	}),
	Parts: Object.freeze({
		key: 'parts',
		apiBase: '/plants/parts',
		routeBase: '/parts',
		filtersStorageKey: 'parts_filters',
		itemsName: Object.freeze({
			one: 'Part',
			mult: 'Parts',
			instanceName: 'parts',
		}),
		permissions: Object.freeze({
			view: 'view_misc_parts',
			create: 'create_misc_parts',
			edit: 'edit_misc_parts',
			delete: 'delete_misc_parts',
		}),
	}),
	Plants: Object.freeze({
		key: 'plants',
		apiBase: '/plants',
		routeBase: '/plants',
		filtersStorageKey: 'plants_filters',
		itemsName: Object.freeze({
			one: 'Plant',
			mult: 'Plants',
			instanceName: 'plants',
		}),
		permissions: Object.freeze({
			view: 'view_plants',
			create: 'create_plants',
			edit: 'edit_plants',
			delete: 'delete_plants',
		}),
	}),
	PlantsVendors: Object.freeze({
		key: 'plants_vendors',
		apiBase: '/plants/vendors',
		routeBase: '/plants-vendors',
		filtersStorageKey: 'plants-vendors_filters',
		itemsName: Object.freeze({
			one: 'Vendor',
			mult: 'Vendors',
			instanceName: 'plants_vendors',
			englishPrefix: 'Plants ',
		}),
		permissions: Object.freeze({
			view: 'view_vendors',
			create: 'create_vendors',
			edit: 'edit_vendors',
			delete: 'delete_vendors',
		}),
	}),
	Processes: Object.freeze({
		key: 'processes',
		apiBase: '/plants/conveyor/processes',
		routeBase: '/processes',
		filtersStorageKey: 'processes_filters',
		itemsName: Object.freeze({
			one: 'Process',
			mult: 'Processes',
			instanceName: 'processes',
		}),
		permissions: Object.freeze({
			view: 'view_oee',
			create: 'create_oee',
			edit: 'edit_oee',
			delete: 'delete_oee',
		}),
	}),
	ProductionLines: Object.freeze({
		key: 'production_lines',
		apiBase: '/production-lines',
		routeBase: '/production-lines',
		filtersStorageKey: 'production_lines_filters',
		itemsName: Object.freeze({
			one: 'Production_Line',
			mult: 'Production_Lines',
			instanceName: 'production_lines',
		}),
	}),
	Teams: Object.freeze({
		key: 'teams',
		apiBase: '/team',
		routeBase: '/teams',
		filtersStorageKey: 'teams_filters',
		itemsName: Object.freeze({
			one: 'Team',
			mult: 'Teams',
			instanceName: 'teams',
		}),
		permissions: Object.freeze({
			view: 'view_users_teams',
			create: 'create_users_teams',
			edit: 'edit_users_teams',
			delete: 'delete_users_teams',
		}),
	}),
	Users: Object.freeze({
		key: 'users',
		apiBase: '/users',
		routeBase: '/users',
		filtersStorageKey: 'users_filters',
		itemsName: Object.freeze({
			one: 'User',
			mult: 'Users',
			instanceName: 'users',
		}),
		permissions: Object.freeze({
			view: 'view_users',
			create: 'create_users',
			edit: 'edit_users',
			delete: 'delete_users',
		}),
	}),
});
