export default {
	common: {
		select: 'Seleccionar',
		back: 'atrás',
		search: 'búsqueda',
		compare: 'comparar',
		clear: 'borrar',		role: 'puesto',
		add: 'agregar',
		edit: 'editar',
		remove: 'quitar',
		delete: 'borrar',
		view: 'ver',
		submit: 'enviar',
		all: 'Todo',
		show: 'Mostrar',
		hide: 'Ocultar',
		name: 'Nombre',
		showing: 'Mostrando',
		to: 'a',
		of: 'de',
		loading: 'cargando',
		saving: 'guardando',
		save: 'guardar',
		type: 'tipo',
		address: 'Dirección',
		mac_address: 'Dirección MAC',
		phone: 'Teléfono',
		info: 'Información',
		reconnect: 'Reconectar',
		offline: 'Desconectado',
		success: 'Éxito',
		time: 'Tiempo',
		names: 'Nombres',
		last: 'Anterior',
		current: 'Actual',
		yes: 'Sí',
		no: 'No',
		cancel: 'Cancelar',
		every: 'Cada',
		week: 'semana',
		month: 'mes',
		year: 'año',

		details: 'Detalles',
		details_pre: 'Detalles de',
		description: 'descripción',
		period: 'Periodo',
		periodic: 'Periódico',
		operations: 'Operaciones',
		plant: 'planta',
		plants: 'plantas',
		plant_s: 'planta(s)',
		production_line: 'Línea de Producción',
		line: 'Línea', // production line
		production_lines: 'Líneas de Producción',
		prod_line: 'L. de Producción',
		utility: 'Utilidad',
		utilities: 'Utilidades',
		machine: 'Máquina',
		machines: 'Máquinas',
		asset: 'Activo',
		assets: 'Activos',
		item: 'Objeto',
		items: 'Objetos',
		work_order: 'Órden de Trabajo',
		recurring_work_order: 'Órden de Trabajo Recurrente',
		work_orders: 'Órdenes de Trabajo',
		maintenance_log: 'Registro de Mantenimiento',
		maintenance_logs: 'Registros de Mantenimiento',
		location: 'Ubicación',
		locations: 'Ubicaciones',
		company: 'Compañía',
		companies: 'Compañías',
		controllers: 'Controladores',
		controller_s: 'Controlador(es)',
		controller: 'Controlador',
		sensors: 'Sensores',
		sensor: 'Sensor',
		sensor_s: 'Sensor(es)',
		teams: 'equipos',
		team: 'equipo',
		users: 'usuarios',
		user: 'usuario',
		creator: 'Creador',
		customer: 'Cliente',
		technician: 'Técnico',
		technicians: 'Técnicos',
		region: 'Región',
		renewal_date: 'Fecha de Renovación',
		im_csm: 'CSM IM',
		champions: 'Contactos',
		distributors: 'distribuidores',
		distributor: 'distribuidor',
		vendors: 'proveedores',
		vendor: 'proveedor',
		requisition: 'orden de compra',
		requisitions: 'órdenes de compra',
		task_procedures: 'procesos de Pasos Múltiples',
		task_procedure: 'proceso de Paso',
		work_order_type: 'tipo de orden de trabajo',
		work_order_types: 'tipos de órdenes de trabajo',
		work_stations: 'estaciones de trabajo',
		work_station: 'Estación de Trabajo',
		brands: 'Marcas de los Equipos',
		brand: 'Marca de los Equipo',
		part_numbers: 'Números de Parte',
		part_number: 'Número de Parte',
		model_number: 'Número de Modelo',
		io_parameters: 'Parámetros de E/S',
		item_types: 'tipos de objeto',
		item_type: 'tipo de objeto',
		categories: 'categorías',
		category: 'categoría',
		applications: 'Aplicaciones',
		application: 'Aplicación',
		storerooms: 'almacenes',
		storeroom: 'almacén',
		storeroom_location: 'Ubicación de almacén',
		location_on_plant: 'Ubicación en planta',
		location_in_plant: 'Ubicación en planta',
		location_on_machine: 'Ubicación en máquina',
		equipment_brand: 'Marca del Equipo',
		equipment_brands: 'Marcas del Equipo',
		requisition_plant: 'Planta de la Orden de Compra',
		lubematrix: 'Lubematrix',
		pdm: 'PDM',
		ncd: 'NCD',
		export: 'Exportar',
		cities: 'Ciudades',
		part: 'Parte',
		main_dashboard: 'Tablero Principal',
		meeting_tracker: 'Registro de Reuniones',
		roi_one_pager: 'ROI a Una Página',
		roi_one_pagers: 'ROIs a Una Página',
		customer_success_dashboard: 'Tablero de Éxito del Cliente',
		downtime: 'Tiempo de Inactividad',
		lost: 'perdidos',
		minutes: 'minutos',
		seconds: 'segundos',
		min: 'min',
		action: 'Acción',
		actions: 'Acciones',
		file: 'archivo',
		image: 'imagen',
		images: 'imágenes',
		roi: 'ROI',
		roi_final: 'ROI final',
		started_at: 'Comenzó a las',
		finished_at: 'Terminó a las',
		status: 'Estado',
		attachments: 'Archivos Adjuntos',
		priod: 'Periodo',
		frequency: 'Frecuencia',
		period_range: 'Rango del Periodo',
		period_dates: 'Fechas del Periodo',
		snooze: 'Pausar Alarmas',
		parts: 'Partes',
		equipment: 'Equipo',
		equipments: 'Equipos',
		change: 'Cambiar',
		task: 'tarea',
		close: 'Cerrar',
		wo: 'O de T',
		logs: 'Registros',
		today: 'Hoy',

		continue: 'Continuar',
		assigned: 'Asignado',
		date: 'Fecha',
		expected_time: 'Tiempo Esperado',
		notes: 'Notas',
		quantity: 'Cantidad',
		due_date: 'Fecha de Entrega',
		due_this_week: 'Entrega esta semana',
		due_today: 'Entrega el día de Hoy',
		late: 'Tarde',
		complete: 'Completo',
		created: 'Creado',
		create: 'Crear',
		denied: 'Denegado',
		approve: 'Aprobar',
		solved: 'Resuelto',
		hours: 'Horas',
		sec: 'seg',
		budget: 'Presupuesto',
		budget_cost: 'Costo del Presupuesto',
		fab_shop_budget: 'Presupuesto del Taller de Fabricación',
		running_total: 'Total Acumulado',
		time_left: 'Tiempo restante',
		graph: 'Gráfica',
		breakdown_machines: 'Máquinas Averiadas',
		day: 'Día',
		days: 'Días',
		afternoon: 'Tarde',
		night: 'Noche',
		breakdown: 'Avería',
		shift: 'cambiar',
		unlock: 'ABRIR',
		print: 'Imprimir',
		start: 'Comenzar',
		finish: 'Terminar',
		id: 'Identificación',
		log: 'Registro',
		files: 'Archivos',
		unapprove: 'Desaprobar',
		on_hold: 'En Espera',
		off_hold: 'Fuera de Espera',
		po: 'O de C', //should be same
		apply: 'aplicar',
		calculate: 'calcular',
		comments: 'Comentarios',
		comment: 'Comentario',
		main: 'Principal',
		menu: 'Menú',
		sso: 'SSO',
		saml: 'SAML',
		enable: 'Habilitar',
		move: 'Mover',
		quote: 'Cotizar',
		service: 'Servicio',
		crossover: 'Reemplazo',
		specifications: 'Especificaciones',
		history: 'Historia',
		specs: 'Especificaciones',
		pdm_item: 'Objeto de MPD',
		pdm_items: 'Objetos de MPD',
		threshold: 'Límite',
		thresholds: 'Límites',
		reset: 'Restaurar',
		for: 'para',
		download: 'descargar',
		axis: 'Eje',
		params: 'Parámetros', //otherwise params is fine
		split: 'Separar',
		warning: 'Aviso',
		order: 'Orden',
		hello: 'Hola',
		prodlines: 'Líneas de Producción',
		process: 'Proceso',
		processes: 'Procesos',
		libraries: 'Bibliotecas',

		// --------------new--------------
		send: 'Enviar',
		enter: 'Ingresar',
		disable: 'Inhabilitar',
		disabled: 'Inhabilitado',
		performed: 'Realizada',
		downloaded: 'descargado',
		processing: 'Procesando',
		working: 'Trabajando',
		pump: 'Bombear',
		pumps: 'Bombeos',
		node: 'Nodo',
		radio_node: 'Nodo de radio',
		radio_nodes: 'Nodos de radio',
		fft: 'FFT',
		ffts: 'FFTs',
		error: 'Error',
		errors: 'Errores',
		fault: 'Falla',
		faults: 'Fallas',
		import_log: 'Registro de Importación',
		import_logs: 'Registros de Importación',
		back_end_Register: 'Registro de Back-End',
		back_end_Registers: 'Registros de Back-End',
		custom_formula: 'Fórmula Personalizada',
		custom_formulas: 'Fórmulas Personalizadas',
		email_template: 'Plantilla de Correo Electrónico',
		email_templates: 'Plantillas de Correo Electrónico',
		industrial_service: 'Servicio Industrial',
		industrial_services: 'Servicios Industriales',
		lube_type: 'Tipo de Lubricante',
		lube_types: 'Tipos de Lubricante',
		in_system: 'En el Sistema',
		authorization: 'Autorización',
		new: 'nuevo',
		with: 'con',
		chart: 'Tabla',
		capacity: 'capacidad',
		data: 'datos',
		go: 'Ir',
		warnings: 'Advertencias',
		templates: 'Plantillas',
		page: 'Página',
		gain: 'Ganancia',
		toggle: 'Alternar',
		on: 'Encendido',
		off: 'Apagado',
		high_speed: 'Alta Velocidad',
		purge_mode: 'Modo de Purga',
		trigger: 'Desencadenar',
		lube_cycle: 'Ciclo de Lubricación',
		cycle: 'ciclo',
		lubrication: 'Lubricación',
		stop: 'Interrumpir',
		stopped: 'interrumpido',
		started: 'comenzado',
		has: 'ha',
		increase: 'Aumentar',
		decrease: 'Disminuir',
		end: 'Fin',
		external_sensor: 'Sensor Externo',
		count: 'Conteo',
		input: 'entrada',
		value: 'valor',
		values: 'valores',
		entity: 'entidad',
		example: 'ejemplo',
		number: 'número',
		system: 'sistema',
		time_zone: 'Zona horaria',
		method: 'método',
		code: 'Código',
		router_number: 'Número de enrutador',
		version: 'Versión',
		report: 'Reporte',
		reports: 'Reportes',
		personal: 'Personal',
		port: 'Puerto',
		expression: 'Expresión',
		dataset: 'Conjunto de datos',
		rpm: 'RPM',
		rating: 'Clasificación',
		position: 'Posición',
		setup: 'Configuración',
		scope: 'Alcance',
		last_name: 'Apellido',
		typing: 'escribiendo',
		minus: 'menos',
		plus: 'mas',
		predefined: 'Predefinido',
		title: 'Título',
		key: 'clave',
		confirm: 'Confirmar',
		admins: 'Administradores',
		stage: 'Etapa',
		timerange: 'rango de tiempo',
		cost: 'Costo',
		material: 'Material',
		rate: 'Tasa',
		pack: 'Paquete',
		mode: 'Modo',
		cartridge: 'Cartucho',
		amount: 'Monto',
		bearing: 'Rodamiento',
		parameters: 'Parámetros',
		parameter: 'Parámetro',
		rules: 'Reglas',
		alert: 'Alerta',
		comparison: 'Comparación',
		graco_pump: 'Graco-pump',
		language: 'Idioma',
		media: 'Medios',
		option: 'Opción',
		predefined_value: 'Valor Predefinido',
		predefined_values: 'Valores Predefinidos',
		is_rpm: 'Es RPM',
		is_fla: 'Es FLA',
		run_rate: 'Tasa de Operación',
		stop_time: 'Tiempo de Paro',
		work_days: 'Días de trabajo',
		work_time: 'Tiempo de trabajo',
		breaktime: 'Descanso',
		cofigure: 'Configurar',
		script: 'Script',
		login: 'Acceso',
		logout: 'Cerrar sesión',
		city: 'Ciudad',
		state: 'Estado',
		country: 'Pais',
		drive_type: 'Tipo de Unidad',
		custom: 'Personalizada',
		field: 'Campo',
		fields: 'Campos',
		supervisor: 'Supervisor',
		logo: 'Logo',
		measurement: 'Medida',
		billing_plan: 'Plan de Facturación',
		email_list: 'Lista de Correo',
		contact: 'Contacto',
		email: 'Correo electrónico',
		one_click: 'un click',
		for_buy: 'para compra',
		for_service: 'para servicio',
		equipment_types: 'Tipos de equipo',
		break_time: 'Descanso',
		origin_type: 'Tipo de origen',
		loss_count: 'Conteo de pérdida',
		max: 'máximo',
		solenoids: 'Solenoides',
		fab_plant: 'Planta de Fabricación',
		work_type: 'Tipo de Trabajo',
		materials: 'Materiales',
		additional: 'Adicional',
		tracking: 'Rastreo',
		shipping: 'Envío',
		note: 'Nota',
		periods: 'Períodos',
		months: 'Meses',
		recommended: 'Recomendado',
		rebaseline: 'Reestablecer Línea de Base',
		archive: 'Archivar',
		power: 'Poder',
		vertical: 'Vertical',
		horizontal: 'Horizontal',
		axial: 'Axial',
		lubricator: 'Lubricador',
		configuration: 'Configuración',
		information: 'Información',
		grease_pack: 'Cartucho',
		density: 'Densidad',
		lubricant: 'Lubricante',
		level: 'Nivel',
		replenishment: 'Reabastecimiento',
		lube_sets: 'Conjuntos de Lubricación',
		lube_cycles: 'Ciclos de Lubricación',
		starting_at: 'Comenzando en',
		data_set: 'Conjunto de Datos',
		register: 'Registrar',
		vibration: 'Vibración',
		password: 'Contraseña',
		notifications: 'Notificaciones',
		sms: 'SMS',
		push: 'Push',
		request: 'Solicitud',
		type_options: 'TYPE OPTIONS',
		total: 'total',
		money: 'Dinero',
		actual_cost: 'Costo Real',
		low_limit: 'Límite Bajo',
		high_limit: 'Límite Alto',
		deadband: 'Deadband',
		re_baseline: 'Re-baseline',
		successfull: 'Exitoso',
		successfully: 'Exitosamente',
		requesting: 'Solicitando',
		deny: 'Denegar',
		requested_completion: 'Finalización Solicitada',
		requestor: 'Solicitante',
		requestor_plant: 'Planta Solicitante',
		equipment_details: 'Detalles del Equipo',
		plant_name: 'Nombre de la Planta',
		reconnection: 'Reconexión',
		reboot: 'Reiniciar',
		convert: 'Convertir',
		reject: 'Rechazar',
		redirect: 'Redireccionar',
		archived: 'Archivado',
		restored: 'Restaurado',
		analogues: 'Análogos',
		alarms: 'Alarmas',
		alarm: 'Alarma',
		width: 'Ancho',
		stock_quantity: 'Existencia',
		contact_name: 'Nombre del contacto',
		date_time: 'Fecha y hora',
		date_sent: 'Fecha de envío',
		requested_date: 'Fecha Solicitada',
		estimated_start_date: 'Fecha Estimada de Inicio',
		estimated_completion_date: 'Fecha Estimada de Finalización',
		machine_name: 'Nombre de la Máquina',
		no_name: 'Sin Nombre',
		asset_number: 'Número de Activo',
		graphs: 'Gráficas',
		sensor_type: 'Tipo de Sensor',
		battery_charge: 'Carga de la Batería',
		connection_strength: 'Fuerza de la Conexión',
		type_of_equipment: 'Tipo de equipo',
		alert_rule: 'Regla de alertas',
		sensor_equipment: 'Equipo de Sensor',
		submitted: 'Enviado',
		wo_Request: 'Solicitud de O de C',
		statistics: 'Estadísticas',
		option_values: 'Valores de opción',
		media_values: 'Valores de los medios',
		formula: 'Fórmula',
		formulas: 'Formulas',
		options: 'Opciones',
		billing_plan_cost: 'Costo del Plan de Facturación',
		form: 'Formato',
		recurring_work_orders: 'Órdenes de Compra Recurrentes',
		filter: 'Filtrar',
		sender: 'Remitente',
		full_name: 'Nombre completo',
		drive: 'Accionamiento',
		site: 'Sitio',
		without: 'Sin',
		fab_shop_manager: 'Gerente del Taller de Fabricación',
		requisitioner: 'Requisitioner',
		change_by: 'Cambiar antes de',
		displacement: 'Desplazamiento',
		zone: 'Zona',
		zones: 'Zonas',
		range: 'Rango',
		side: 'Lado',
		ring_direct: 'Anillo/Directo',
		bearings: 'Rodamientos',
		meeting_trackers: 'Rastreadores de Reuniones',
		types: 'Tipos',
		fab: 'Fabricación',
		work_order_request: 'Solicitud de Orden de Trabajo',
		work_order_requests: 'Solicitudes de Órdenes de Trabajo',
		text: 'texto',
		price: 'Precio',
		testing: 'Probando',
		tresholds: 'Límites',
		acceleration: 'Aceleración',
		velocity: 'Velocidad',

		pm: 'MP',
		reason: 'Motivo',
		none: 'Ninguno',
		hour: 'hora',

		parent: 'Parent',
		services: 'Servicios',

		runtime: 'Tiempo de Ejecución',
		last_reset: 'Último Reinicio',
		industrial_matrix: 'Industrial Matrix',
		permission: 'Permission',
		permissions: 'Permissions',
		viewing: 'visualización',
		creating: 'creando',
		updating: 'actualizando',
		updated: 'actualizado',
		deleting: 'eliminando',
		section: 'Sección',
		sections: 'Secciones',
		roles: 'Roles',
		child_roles: 'Roles Secundarios',
		device: 'Dispositivo',
		fmax: 'Fmax',
		amplitude: 'Amplitud',
		notification: 'Notificación',
		linespeed: 'Velocidad de línea',
		overlay: 'Superposición',
		command: 'Comando',
		commands: 'Comandos',
		response: 'Respuesta',
		is_empty: 'Está Vacío',
		standard: 'Estándar',
		envelope: 'Sobre',
		cursor: 'Cursor',
		cursors: 'Cursores',
		peaks: 'Picos',
		step: 'Paso',
		steps: 'Pasos',
		waterfall: 'Cascada',
		radio: 'Radio',
		retry: 'Reintentar',
		rotate: 'Rotar',
		rotation: 'Rotación',
		zoom: 'Zoom',
		drag: 'Arrastrar',
		subtype: 'Subtipo',
		commissioning: 'Comisionamiento',
		default: 'Por Defecto',
		archiving: 'archivando',
		customizable: 'Personalizable',
		signed: 'Firmado',
		speed: 'Velocidad',
		source: 'Fuente',
		exteranal: 'Externo',
		specification: 'Especificación',
		the: 'el',
		serial_number: 'Número de Serie',
		model: 'Modelo',
		firmware_number: 'Número de Firmware',
		force_mfa: 'Forzar MFA',
		old: 'Antiguo',
		authenticator: 'autenticador',
		allow: 'Permitir',
		unknown: 'desconocido',
		overall: 'General',
		summaries: 'Resumenes',
		in_service: 'En Servicio',
		overall_program_review: 'Revisión General del Programa',
		multi_view: 'Vista-Múltiple',
		launch_time: 'Hora de Lanzamiento',
		days_range: 'Rango de Días',
		manually: 'Manualmente',
		baselining: 'Baselining',
		share: 'Compartir',
		column: 'Columna',
		tag: 'Etiqueta',
		fail: 'Fallar',
		low: 'Bajo',
		high: 'Alto',
		areaspline: 'Área-Espline',
		favorites: 'Favoritos',
		child: 'subtipo',
		childs: 'subtipos',
		component: 'Componente',
		components: 'Componentes',
		harmonics: 'Harmónicos',
		editable: 'Editable',
		difference: 'Diferencia',
		devices: 'Dispositivos',
		saved: 'salvado'
	},

	sidebar_menu: {
		predictive_maintenance: 'Mantenimiento Predictivo',
		dashboard: 'Tablero',
		customer_success: 'Éxito del Cliente',
		oee: 'EGE',
		system: 'sistema',
		profile: 'perfil',
		rnd: 'investigación y Desarrollo',
		settings: 'configuración',
		cmms: 'SCGM',
		work_orders_maintenance_logs: 'Órdenes de trabajo & registros de mantenimiento',
		roi_calculator: 'calculadora del ROI',
		work_order_requests: 'solicitudes de orden de compra',
		misc_parts: 'partes',
		work_order_import: 'importar orden de trabajo',
		import: 'importar',
		plant_import: 'importar planta',
		plant_import_logs: 'importar registros de planta',
		master_import: 'importación maestra',
		asset_management: 'manejo de activos',
		library: 'biblioteca',
		work_stations: 'Estaciones de Trabajo',
		categories: 'categorías de tipos de objeto',
		cost_savings_calculator: 'calculadora de ahorro de costos',
		user_roles: 'Roles de Usuario',
		user_role: 'Rol de Usuario',
		import_master: 'importar maestro',
		item_types_categories: 'Categorías de Tipos de Elementos',
		users_teams: 'Equipos de Usuarios',
		corporate_view: 'Vista Corporativa',
	},

	phrases: {
		start_date: 'Fecha Inicio',
		end_date: 'Fecha Fin',
		thresholds_re_baseline: 'Recalculación de Límites',
		it_will_take_some_time: 'Va a tomar algo de tiempo',
		request_fft: 'Solicitar FFT',
		last_fft: 'Última FFT',
		charts_loading: 'Cargando tablas',
		there_are: 'No existen',
		no_charts: 'tablas',
		no_statistics: 'estadísticas',
		for_this_sensor: 'para este sensor',
		show_all: 'Mostrar Todo',
		production_line_without_name: 'Línea de Producción sin nombre',
		edit_machine: 'Editar Máquina',
		production_line_details: 'Detalles de Línea de Producción',
		quote_send: 'Enviar cotización',
		there_are_no_vendors_for_request_selected:
			'No existen proveedores para la solicitud seleccionada',
		one_click_request: 'Solicitud de Un Solo Clic',
		loc_on_machine: 'Ubic en máquina',
		motor_results: 'Resultados del Motor',
		view_all: 'Ver Todo',
		request_for_quotation: 'Solicitud de Cotización',
		request_for_quotations: 'Solicitud de Cotizaciones',
		data_missing_for_crossovers: 'Falta Información Para Sustitutos',
		this_asset_has_not_equipments: 'Este activo no tiene equipos',
		reply_url_claims_service_url:
			'URL de respuesta (URL del Servicio de Reclamaciones)',
		identifier_object_id: 'Identificador (ID del objeto)',
		paste_parameters_from_azure_and_click_button_save:
			'Pegar los parámetros de Azure y hacer clic en el botón "Guardar"',
		section_enter_the_following_information:
			'sección, ingrese la siguiente información',
		basic_saml_configuration: 'Configuración básica de SAML',
		create_a_new_non_gallery_app: 'crear una nueva aplicación que no sea de galería',
		add_industrialmatrix_to_azure_ad: 'Agregar IndustrialMatrix a Azure AD',
		open_your_azure_ad_administrator_account_and:
			'Abra su cuenta de administrador de Azure AD y',
		for_the_new_application: 'Para la nueva aplicación',
		requisition_plant_dashboard: 'Tablero de Solicitudes de Compra de la Planta',
		fab_plant_dashboard: 'Tablero de Fabricaciones de la Planta',
		work_order_company_overview:
			'Descripción General de órdenes de Trabajo de la Empresa',
		repair_cost_avoidance: 'Prevención de Costos de Reparaciones',
		contractor_markup: 'Margen del Contratista',
		contractor_hourly_rate: 'Tarifa por hora del contratista',
		dt_per_hour: 'DT/Hora',
		hours_saved_or_lead_time: 'Horas Ahorradas / Tiempo de Entrega',
		contractor_quote: 'Cotización del Contratista',
		tech_hours: 'Horas de Tecnología',
		date_selection: 'Selección de Fecha',
		date_sent: 'Fecha de Envío',
		requested_date: 'Fecha Solicitada',
		estimated_start_date: 'Fecha de Comienzo Estimada',
		estimated_completion_date: 'Fecha de Término Estimada',
		has_not_statistics_for_this_range: 'No existen Estadísticas para este Rango.',
		select_shift: 'Seleccionar turno',
		edit_work_order: 'Editar Orden de Trabajo',
		work_order_details: 'Detalles de Orden de Trabajo',
		create_work_order_request: 'CREAR SOLICITUD DE ORDEN DE TRABAJO',
		maintenance_log_details: 'Detalles del registro de mantenimiento',
		supervisor_notes: 'Notas del supervisor',
		acknowledge_by_supervisor: 'Reconocido por el supervisor',
		sanitization_of_tools: 'Sanitización de Herramientas',
		problem_solved: 'Problema Resuelto',
		top_5_breakdowns: 'TOP 5 DE AVERÍAS',
		to_view_the_information_of_the_work_order_click_on_the_preview_button_from_the_list_of_work_orders:
			'Para ver la información de la orden de trabajo, haga clic en el botón de vista previa de la lista de órdenes de trabajo',
		open_details: 'Abrir Detalles',
		this_will_set_in_work_status_to_selected_workorders:
			'Esto establecerá el estado Trabajando para las Órdenes de Trabajo seleccionadas',
		this_will_complete_selected_workorders:
			'Esto completará las Órdenes de Trabajo seleccionadas',
		this_will_close_selected_workorders:
			'sto cerrará las Órdenes de Trabajo seleccionadas',
		creation_is_not_allowed: 'No está permitida la creación',
		wo_name: 'Nombre de O de T',
		required_items: 'Objetos requeridos',
		in_work: 'Trabajando',
		from_request: 'De Solicitud',
		assigned_to_me: 'Asignado a mí',
		change_status: 'Cambiar Estado',
		assigned_to: 'Asignado a',
		create_work_order_type: 'Crear Tipo de Orden de Trabajo',
		please_check_fields_errors_first:
			'Por favor verifique los errores de los campos',
		Apply_this_action_to_all_reccurring_orders_or_only_this_one:
			'Aplicar esta acción a todos los pedidos recurrentes o solamente a este',
		to_all: 'A todos',
		only_this_one: 'Solamente a este',
		create_part: 'Crear Parte',
		technician_users: 'Usuarios para Técnicos',
		teams_in_the_plant: 'Equipos en la planta',
		at_least_one_of_these_fields_is_required:
			'Se requiere por lo menos uno de estos campos',
		show_procedures: 'Mostrar procedimientos',
		parts_from_procedure: 'Partes del procedimiento',
		snooze_alerts: 'Pausar Alertas',
		upload_files: 'Cargar archivos',
		work_order_name: 'Nombre de Orden de Trabajo',
		select_date: 'Seleccionar fecha',
		statistics_for_period: 'Estadísticas para el periodo',
		select_plant_first: 'Seleccionar primero la planta',
		select_company_first: 'Seleccionar primero la compañía',
		choose_plant_first: 'Escoger primero la planta',
		data_driven_recommended_actions:
			'Acciones Recomendadas Basadas en la Información',
		data_driven_issues_resolved: 'Problemas Resueltos Basados en la Información',
		last_3_months: 'Últimos 3 meses',
		ydt: 'Último Año',
		last_12_months: 'Últimos 12 meses',
		overall_asset_health: 'Estado General de los Activos',
		roi_value_creation: 'ROI/Creación de Valor',
		no_data: 'SIN INFORMACIÓN',
		create_work_order: 'Crear Orden de Trabajo',
		view_machines: 'Ver Máquinas',
		show_binding_machines: 'Mostrar Máquinas Vinculadas',
		edit_line: 'Editar Línea',
		asset_without_name: 'Activo sin nombre',
		part_number_without_name: 'Número de Parte sin nombre',
		not_found: 'No se encontraron',
		show_binding_items: 'Mostrar Objetos Vinculados',
		move_to_storeroom: 'Mover al Almacén',
		move_item: 'Mover Objeto',
		equipments_count: 'Conteo de Equipos',
		models_count: 'Conteo de Modelos',
		view_sensors: 'Ver Sensores',
		edit_item: 'Editar Objeto',
		lube_cycle_was_reset: 'Se Reestableció el Ciclo de Lubricación',
		spent_shots_was_reset: 'Se Reiniciaron los Disparos',
		grease_pack_was_reset: 'Se Reinició el Paquete de Grasa',
		reset_cycle: 'Reestablecer Ciclo',
		clear_filters: 'Eliminar Filtros',
		display_archived_sensors: 'Mostrar Sensores Archivados',
		issues_detected: 'Problemas Detectados',
		issues_resolved: 'Problemas Resueltos',
		lube_delivered: 'Lubricación Aplicada',
		lube_cycles_auto: 'Ciclos de Lubricación Automáticos',
		unsuccessful_autolube: 'Autolubricación No Exitosa',
		autolube_alarm: 'Alarma de Autolubricación',
		lube_cycles_manual: 'Manual de Ciclos de Lubricación',
		automatic_ffts_generated: 'FFT’s Generados Automáticamente',
		reset_lube: 'Reiniciar Lubricador',
		luber_empty: 'Lubricador Vacío',
		reset_grease_pack: 'Reestablecer el Paquete de Grasa',
		sensor_statistics: 'Estadísticas del Sensor',
		add_to_compare_list: 'Agregar a lista de comparar',
		all_storerooms: 'Todos los almacenes',
		all_storeroom_locations: 'Todas las ubicaciones de almacenes',
		select_alert_types: 'Seleccionar tipos de alertas',
		show_binding_assets: 'Mostrar Activos Vinculados',
		all_statistics: 'Todas las Estadísticas',
		asset_health_score: 'Calificacipon de la Salud del Activo',
		time_in: 'Tiempo',
		to_do: 'POR HACER',
		sensors_offline: 'Sensores Sin Conexión',
		activities_completed_this_week_period:
			'Actividades Completadas esta semana/periodo',
		activities_planned_for_next_week_period:
			'Actividades planeadas para la siguiente semana/periodo',
		asset_monitoring: 'Monitoreo de Activos',
		recommended_actions: 'Acciones Recomendadas',
		activities_in_progress: 'Actividades en Progreso',
		success_expansion_plans: 'Planes de Expansión de Éxito',
		recurring_issues_continuous_issue_discussion:
			'Problemas recurrentes/discusión de problema continuo',
		roi_value_creation_summary: 'ROI/Resumen de Creación de Valor',
		questionnaire_form: 'Formulario de Cuestionario',
		customer_product_feedback: 'Comentarios Sobre el Producto del Cliente',
		save_send: 'guardar&enviar',
		completed_rois: 'ROIs Completados',
		roi_salvings_ca: 'Ahorros de ROI/PC',
		of_sensors: '# de Sensores',
		next_launch_date: 'Próxima Fecha de Lanzamiento',
		created_at: 'Creado el',
		export_to_pdf: 'Exportar a PDF',
		form_isnt_ready: 'La Forma no está lista',
		please_check_phone_number_form_field_first:
			'Por favor verifique el campo del de número de teléfono',
		meeting_tracker_date: 'Fecha del Seguimiento de la Reunión',
		name_is_missing: 'Falta el nombre',
		findings_issue_detection_action_plan:
			'Descubrimientos/Detección de Problemas & Plan de Acción',
		roi_cost_avoidance: 'ROI/Prevención de Costos',
		pdm_data_screenshot: 'Captura de Pantalla de la Información de PDM',
		history_roi_one_pager: 'ROI Histórico a una Página',
		roi_ca_$: 'ROI/CA $',
		production_line_name: 'Nombre de la Línea de Producción',
		machine_name: 'Nombre de la máquina',
		asset_name: 'Nombre del activo',
		open_pdf_file: 'Abrir archivo PDF',
		do_you_really_want_to: '¿Estás seguro que deseas',
		action_continue: 'acción? Continuar?',
		total_time: 'Tiempo total',
		select_daterange_first: 'Primero seleccionar rango de fechas',
		high_alarm: 'Alarma Alta',
		low_alarm: 'Alarma Baja',
		amplitude_alarm: 'Alarma Amplitud',
		possible_problems: 'Posibles problemas',
		setup_thresholds: 'Ajustar límites',

		// --------------new--------------
		mismatch_in_sensor_type_please_check_configuration:
			'No coincide el tipo de sensor; verifique la configuración',
		roi_final_should_be_a_number: 'El ROI final debe ser un número',
		file_is_required: 'Se requiere archivo',
		selection_out_of_chart_range: 'Selección fuera del rango de la gráfica',
		you_do_not_have_permissions_to_save: 'Usted no tiene permiso para guardar',
		restricted_actions: 'Acciones restringidas',
		choose_a_different_axis: 'Escoja un eje diferente',
		working_config: 'Configuración de Funcionamiento',
		ncd_config_saved_successfully: 'Configuración NCD Guardada Correctamente',
		gain_adjustment_successful: 'Ajuste de Ganancia Exitoso',
		gain_adjustment_failed: 'Error en el Ajuste de Ganancia',
		controller_timeout: 'Tiempo de Espera del Controlador',
		command_sent_successfully: 'Comando Enviado Exitosamente',
		doesn_t_exists: 'no existe',
		error_check_controller_connectivity:
			'Error - Comprobar la Conectividad del Controlador',
		sensor_created_successfully: 'Sensor Creado Exitosamente',
		web_socket_error: 'Error de Conexión Web',
		should_be_assigned: 'debería estar asignado',
		data_isn_t_ready: 'La información no está disponible',
		total_time_should_be_15_minutes: 'El tiempo total debe ser mayor a 15 minutos',
		is_required: 'se requiere',
		check_form_fields: 'Comprobar campos del formulario',
		validation_error: 'Error de validacion',
		reverting_attempt_unsuccessfull: 'Revertir Intento no fue Exitoso',
		view_line_details: 'Ver Detalles de Línea',
		disable_off_alarm: 'Desactivar Alarma Desactivada',
		reject_this_work_order_request: 'Rechazar esta Solicitud de Orden de Trabajo',
		see_work_order_request: 'Ver Solicitud de Orden de Trabajo',
		apply_this_action_to_all_reccurring_orders_or_only_this_one:
			'Aplicar esta acción a todos los pedidos recurrentes o solo a este',
		close_this_work_order: 'Cerrar esta Orden de Trabajo',
		this_will_complete_selected_workOrders:
			'Esto completará las Órdenes de Trabajo seleccionadas.',
		this_will_permanently_delete_selected:
			'Esto eliminará permanentemente la selección',
		this_will_permanently_delete_current: 'Esto eliminará permanentemente la actual',
		clear_logs: 'Borrar registros',
		new_configure: 'Nueva Configuración',
		new_script: 'Nuevo Guión',
		do_this_action_for: 'Realizar esta acción para',
		delete_this_option: 'Eliminar esta Opción',
		expected_receive_date: 'Fecha Esperada de Recepción',
		shipping_method: 'Método de Envío',
		reject_reason: 'Motivo del Rechazo',
		additional_work_order_details: 'Detalles Adicionales de la Orden de Trabajo',
		site_visit_required: '¿Se Requiere Visita al Sitio?',
		do_you_want_to_specify_shipping_details: '¿Desea Especificar Detalles de Envío?',
		this_order: 'esta orden',
		delete_this_requisition: 'Eliminar esta Requisición',
		delete_this_activity: 'Eliminar esta actividad',
		check_controller_connectivity: 'Verifique la Conectividad del Controlador',
		rebase_line_by_selected_range:
			'Renovar base de la Línea por el rango seleccionado',
		import_log_is_empty: 'El registro de importación está vacío',
		low_pass_filter: 'Filtro de Paso Bajo',
		high_pass_filter: 'Filtro de Paso Alto',
		enable_filtering: 'Habilitar Filtrado',
		sample_duration: 'Duración de la Muestra',
		output_data_rate: 'Velocidad de Datos de Salida',
		frequency_range: 'Rango de Frecuencia',
		sensor_boot_time: 'Tiempo de Arranque del Sensor',
		connection_strength_trend: 'Tendencia de Fuerza de Conexión',
		connection_strength_average: 'Promedio de Fuerza de Conexión',
		view_graph: 'Ver Gráfica',
		custom_level_alarm: 'Alarma de Nivel Personalizado',
		critical_alarm: 'Alarma Crítica',
		adding_notes_notifications: 'Agregar Notificaciones de Notas',
		email_notifications: 'Notificaciónes de Correo Electrónico',
		daily_summary_sensor_notifications:
			'Resumen Diario de las Notificaciones de Sensores',
		real_time_sensor_notifications: 'Notificaciones de Sensores en Tiempo Real',
		daily_summary_notify_at: 'Notificar el Resumen Diario en',
		hourly_rate: 'Tarifa por Hora',
		daily_summary: 'Resumen Diario',
		is_receive_sensors_anomaly_notifications:
			'Se reciben notificaciones de anomalías de los sensores',
		notifiable_plants: 'Plantas notificables',
		first_name: 'Nombre',
		last_name: 'Apellidos',
		actual_lubricant_per_cycle: 'Lubricante Real por Ciclo',
		lubricant_dilevered_per_cycle: 'Lubricante Enviado por Ciclo',
		target_lubricant_per_cycle: 'Lubricante Objetivo por Ciclo',
		total_lubricant_dilevered_in_all_sets:
			'Lubricante Total Enviado en Todos los Juegos',
		lube_cycle_dwell_time: 'Tiempo de Permanencia del Ciclo de Lubricante',
		time_between_lube_sets_sec: 'Tiempo Entre Juegos de Lubricación (seg)',
		time_between_lube_cycles_sec: 'Tiempo Entre Ciclos de Lubricación (seg)',
		lube_cycles_per_set: 'Ciclos de Lubricación por Juego',
		calculated_lube_sets: 'Juegos de Lubricación Calculados',
		calculated_time: 'Tiempo Calculado',
		calculated_cycles_per_set: 'Ciclos Calculados Por Juego',
		apply_calculated_data: 'Aplicar datos calculados',
		lube_logic_setup: 'Configuración de la Lógica de Lubricación',
		target_lubricant_per_set: 'Lubricante Objetivo Por Juego',
		lubricant_delivered_per_set: 'Lubricante Enviado Por Juego',
		actual_lubricant_per_set: 'Lubricante Real Por Juego',
		total_lubricant_delivered_in_all_sets:
			'Lubricante Total Enviado en Todos los Juegos',
		lube_cycles_per_cartridge: 'Ciclos de Lubricación Por Cartucho',
		lube_cycle_spent_count: 'Conteo del Gasto del Ciclo de Lubricación',
		calculated_lubricated_quantity: 'Cantidad Lubricada Calculada',
		outside_diameter: 'Diámetro Exterior',
		hide_vertical_axis_rms: 'Ocultar RMS del Eje Vertical',
		reason_denied: 'Motivo Denegado',
		see_visit_required: 'Visita Requerida?',
		notifications_for: 'Notificaciones para',
		industrial_services: 'Servicios Industriales',
		equipment_breakdown: 'Desglose del Equipo',
		installed_at: 'Instalado en',
		without_brand: 'Sin Marca',
		extended_work_date: 'Fecha de Trabajo Extendida',
		stop_time_tooltip:
			'Aquí es cuando el conteo recibido son 0s y debe activarse según la cantidad de 0s seguidos que recibamos',
		further_below_run_rate_tooltip:
			'Este es un promedio acumulado de una desaceleración en la que se detectó una desviación adicional más allá del promedio general de la desaceleración original',
		acute_samples: 'Muestras agudas',
		stable_samples: 'Muestras estables',
		samples_to_alarm: 'Muestras para Alarma',
		samples_to_settle: 'Muestras para liquidar',
		commucate_method: 'Método de comunicación',
		connection_type: 'Tipo de Conexión',
		binding_code: 'Código de Vinculación',
		cloud_connection_type: 'Tipo de Conexión a la Nube',
		router_sim_card_number: 'Número de Tarjeta SIM del Enrutador',
		router_serial_number: 'Número de Serie del Enrutador',
		measuring_system: 'Sistema de medición',
		azure_ad_identifier: 'Identificador de Azure AD',
		move_to: 'Mover Hacia',
		type_option_values: 'Teclee los valores de las opciones',
		type_media_values: 'por favor escriba los valores de los medios',
		further_below_run_rate_percent:
			'Más por Debajo de la Tasa de Ejecución (porcentaje)',
		crossover_exluded: 'Reemplazo excluido',
		no_file_loaded: 'Ningún archivo cargado',
		add_to_completed_this_week: 'Agregar a Completado esta semana',
		add_to_recommended_actions: 'Agregar a Acciones Recomendadas',
		add_to_activities_planned_for_next_week_period:
			'Agregar a Actividades planeadas para la próxima semana/período',
		type_of_equipments: 'Tipo de Equipos',
		site_visit: 'Visita al sitio',
		select_equipment_whose_order_you_want_to_reset:
			'Seleccione el equipo cuyo orden desea restablecer',
		whose_order_you_want: 'cuyo orden desea',
		convert_to_predefined: 'Convertir a predefinido',
		show_in_filter: 'Mostrar en filtro',
		show_in_item: 'Mostrar en el objeto',
		show_in_analysis: 'Mostrar en el análisis',
		crossover_rule_type: 'Tipo de Regla de Remplazo',
		sensor_parameter: 'Parámetro del sensor',
		for_incoming_registers: 'Para registros entrantes',
		reverse_formula: 'Fórmula inversa',
		click_to_upload: 'Haga clic para cargar',
		upload_file: 'Subir archivo',
		the_sensor_gain: 'La Ganancia del Sensor',
		manual_lubrication_command_sent: 'Comando de lubricación manual enviado',
		purge_mode_is: 'El Modo de Purga está', // on/off
		requisition_form: 'Formulario de Solicitud',
		spectrum_analysis: 'Análisis de Espectro',
		plant_dashboard: 'Panel de Control de la Planta',
		existing_sensors: 'Sensores existentes',
		group_data_by: 'Agrupar datos por',
		loss_count: 'Conteo de pérdidas',
		accumulative_downtime: 'Tiempo de Inactividad Acumulativo',
		maximum_capacity: 'Maxima capacidad',
		realistic_capacity: 'Capacidad realista',
		import_process_funished_successfully:
			'El proceso de importación finalizó exitosamente',
		loaded_results_from_file: 'Resultados cargados desde el archivo',
		machine_without_name: 'Máquina sin nombre',
		reset_sensor: 'Restablecer sensor',
		gain_signal_value: 'Valor de señal de ganancia',
		extra_vibration_threshold_multipliers:
			'Multiplicadores de umbral de vibración adicionales',
		alarm_zone_should_be_higher_than_warning_zone:
			'La zona de alarma debe ser más alta que la zona de advertencia',
		all_threshold_multipliers_fields_should_have_values:
			'Todos los campos de multiplicadores de umbral deben tener valores',
		fft_locked_out_remaining_time: 'FFT Bloqueado - Tiempo Restante',

		// --------------new 2--------------
		see_maintenance_log: 'Ver Registro de Mantenimiento',
		to_be_discussed: 'Por ser discutido',
		you_are_not_authorized_to_view_this_page:
			'Usted no está autorizado a ver esta página',
		you_do_not_have_permissions_to_view_this_page:
			'Usted no tiene permiso para ver esta página',
		limited_access: 'Acceso limitado',
		not_authorized: 'No autorizado',
		try_sign_in_again: 'Intente iniciar sesión nuevamente',
		load_more: 'Cargar más',
		create_item_first: 'Primero crear el objeto',
		equipment_name: 'Nombre del Equipo',
		expected_time: 'Tiempo Esperado',
		radio_node_position: 'Posición del nodo de radio',
		additional_details: 'Detalles Adicionales',
		gain_adjustment_failure: 'Error de ajuste de ganancia',
		sensor_gain_increased: 'Aumentó la Ganancia del sensor',
		sensor_gain_decreased: 'Disminuyó la Ganancia del sensor',
		sensor_gain_reset: 'Se Reestableció la Ganancia del sensor',
		gain_adjustment_controller_timeout:
			'Tiempo de espera del controlador de ajuste de ganancia',
		unable_to_verify_lube_cycle: 'No se puede Verificar el Ciclo de Lubricante',
		view_file: 'Ver Archivo',
		scheduled_start_date_and_time_required: 'Fecha y hora de inicio requerida',
		add_new_note_to_point: 'Agregar nueva nota al punto',

		// --------------new 3--------------
		file_was_sent_on_your_email: 'El archivo se envio a su correo electronico',
		select_date_range_first: 'Seleccione primero un rango de fecha',
		percentage_of_points_above_alarm: 'Porcentaje de puntos sobre la alarma',
		cool_down_time_minutes: 'Tiempo de enfriamiento (minutos)',
		warm_up_time_minutes: 'Tiempo de calentamiento (minutos)',
		modes_of_cycles: 'Modos de ciclos',

		equipment_breakdown_maintenance_log:
			'Desglose del Equipo/ Registro de Mantenimiento',
		see_parent_work_order: 'Ver Órden de trabajo Principal',
		start_work_order: 'Iniciar Orden de Trabajo',
		cost_savings: 'Ahorro de Costos',
		running_total_materials: 'Total de Materiales Acumulado',
		running_total_hours: 'Total de Horas Acumulado',
		low_cut_filter: 'Filtro de Corte Bajo',
		high_cut_filter: 'Filtro de Corte Alto',
		continue_and_update_alarm_threshold:
			'Continuar y Actualizar el Umbral de Alarma',
		complete_save_and_update_alarm_threshold:
			'Completar/Guardar y Actualizar el Umbral de Alarma',
		continue_or_save_changes: 'Continuar o Guardar cambios',
		unsaved_thresholds: 'Umbrales no guardados',
		export_charts_to_pdf: 'Exportar gráficos a PDF',
		load_last_export: 'Cargar última exportación',
		sensors_should_be_selected: 'Se deben seleccionar los sensores',
		save_progress: 'Guardar Progreso',
		should_be_lower_than: 'debe ser menor que',
		enable_run_hour_tracking_for_sensors:
			'Habilitar Seguimiento de Horas de Funcionamiento para Sensores',
		show_run_hours: 'Mostrar Horas de Funcionamiento',
		runtime_was_reset: 'El Tiempo de Ejecución fue Restablecido',
		run_hour_counter_reset: 'Reinicio del Contador de Horas de Funcionamiento',
		runtime_tracking_threshold_data_value:
			'Valor de Datos del Umbral de Seguimiento de Tiempo de Ejecución',
		reset_frequency_settings: 'Restablecer Configuración de Frecuencia',
		converting_maintenance_request: 'Convirtiendo Solicitud de Mantenimiento',
		request_type: 'Tipo de Solicitud',
		request_fmax: 'Fmax de Solicitud',
		please_select_request_type_and_fmax:
			'Por favor, seleccione el tipo de solicitud y Fmax',
		fft_data_is_not_valid: 'Los datos FFT no son válidos',
		is_google_cloud_data: '¿Es Google Cloud Data?',
		cycles_counter: 'Contador de Ciclos',
		amount_cycles: 'Cantidad de Ciclos',
		should_be_selected: 'debe ser seleccionado',
		disable_iaq: 'Desactivar IAQ',
		command_should_be_filled: 'El comando debe estar lleno',
		time_waveform_full_bandwidth:
			'Forma de onda de tiempo de ancho de banda completo',
		time_waveform_high_frequency_enveloping_hfe_peak_filtering:
			'Forma de onda de tiempo de filtrado de pico de envoltura de alta frecuencia (HFE)',
		sending_fft_request_to_controller: 'Enviando solicitud FFT al controlador',
		is_receive_sensors_anomaly: '¿Recibir anomalías de sensores?',
		adding_notes: 'Agregando notas',
		number_of_graphs: 'Número de gráficos',
		reset_rotation: 'Restablecer Rotación',
		controller_received_the_request_properly:
			'El controlador recibió la solicitud correctamente',
		banner_v2_subtype: 'Subtipo de Banner V2',
		banner_v2_subtypes: 'Subtipos de Banner V2',
		show_archived: 'Mostrar Archivado',
		requisitions_notifications: 'Notificaciones de Requisiciones',
		image_is_required: 'Se requiere imagen',
		successfully_logged_in: 'Se ha iniciado sesión exitosamente',

		devices_attached_to_it: 'Dispositivos adjuntos a él',
		you_need_to_select_rpm_source_first: 'Necesita seleccionar la fuente de RPM primero',
		would_you_like_to_delete_it_anyway: '¿Le gustaría eliminarlo de todos modos',
		please_type: 'Por favor escriba',
		to_confirm: 'para confirmar',
		type_delete_here: 'Escriba "delete" aquí',
		please_type_delete_to_confirm: 'Por favor escriba "delete" para confirmar',
		create_maintenance_log: 'Crear Registro de Mantenimiento',
		script_version: 'Versión del Guión',
		wrong_sensor_firmware_version: 'Versión de firmware del sensor incorrecta',
		lube_version: 'Versión de Lubricante',
		all_values_must_be_a_number: 'Todos los valores deben ser un número',

		password_is_required: 'Se requiere contraseña',
		forgot_password: 'Olvidó su contraseña',
		enter_your_password: 'Ingrese su contraseña',
		send_code: 'Enviar código',
		check_code: 'Verificar código',
		resend_code: 'Reenviar código',
		enter_mfa_code: 'Ingrese el código MFA',
		confirm_password: 'Confirmar contraseña',
		phone_is_required: 'Se requiere teléfono',
		password_must: 'La contraseña debe',
		reports_saved_successfully: 'Informes guardados correctamente',
		start_report_manually: 'Iniciar informe manualmente',
		for_sensors_on_controller: 'Para sensores en el controlador',
		multiple_fft: 'FFT Múltiples',
		running_threshold: 'Umbral de Ejecución',
		joined_at: 'Unido el',
		shots_count_per_today: 'Conteo de Disparos por Hoy',
		total_shots_count: 'Conteo Total de Disparos',
		total_successful_shots_count: 'Conteo Total de Disparos Exitosos',
		total_unsuccessful_shots_count: 'Conteo Total de Disparos No Exitosos',
		all_metrics: 'Todas las Métricas',
		multi_view_charts: 'Gráficos de Vista Múltiple',
		is_report_by_notifiable_plants: '¿Es informe por plantas notificables?',
		report_plants: 'Plantas de informe',
		baseline_delta: 'Delta de Línea Base',
		warning_and_alarm_delta: 'Delta de Advertencia y Alarma',
		notifications_for_all_monitoring_points: 'Notificaciones para todos los puntos de monitoreo',
		sending_lube_cycle_request: 'Enviando solicitud de ciclo de lubricación',
		thresholds_only: 'Solo umbrales',
		report_created: 'Informe creado',
		confirm_phone_number: 'Confirmar número de teléfono',
		fft_successfully_unlocked: 'FFT desbloqueado con éxito',
		unlock_fft: 'Desbloquear FFT',
		sample_metadata: 'Metadatos de la Muestra',
		flat_data_anomaly: 'Anomalia de datos Plano',
		open_in_new_window: 'Abrir en nueva ventana',
		personal_favorite: 'Favorito Personal',
		company_favorite: 'Favorito de la Empresa',
		lube_based_device_address_id: 'ID de dirección de dispositivo de lubricación',
		lube_based_physical_sensor_id: 'ID físico de sensor de lubricación',
		lube_trigger_metric_type: 'Tipo de métrica de disparo de lubricación',
		re_trigger_samples: 'Muestras de re-disparo',
		silence_mode: 'Modo Silencio',
		visible_by_default: 'Visible por defecto',
		silence_mode_until: 'Modo Silencio hasta',
		metric_to_imperial_formula: 'Fórmula de métrica a imperiales',
		imperial_to_metric_formula: 'Fórmula imperial a métrica',
	},

	aliases: {
		rpm_tooltip_prhrase: `Utilice {valor} como valor de velocidad en RPM. <br/>
													Ejemplo: {valor} * 60 + 500`,
		subtype_formula_tooltip: `Utilice {valor} como entrada de la E/S. <br/>
													Ejemplo: {valor} * 60 + 500 <br/>
													Nota: La fórmula original se aplicará antes de esta fórmula.`,
		password_validation: `La contraseña debe contener al menos 8 caracteres, una letra mayúscula, una letra minúscula, un número y un carácter especial Y no ser el mismo que el nombre de su cuenta.`,
		passwords_compar_error: `Las contraseñas no coinciden`,
		mfa_auth_restriction: `La autenticación multifactor (MFA) está habilitada para su cuenta. Por favor, complete la verificación MFA antes de continuar.`,
		reset_pass_msg: 'Se envió un enlace para restablecer la contraseña a su correo electrónico.',
		mfa_code_send_msg: 'Se envió un SMS con un código de verificación a tu teléfono',
		verification_ok: 'Verificación por SMS confirmada',
		pass_req_l_case: 'Tener al menos un carácter en minúscula',
		pass_req_u_case: 'Tener al menos un carácter en mayúscula',
		pass_req_number: 'Tener al menos un número',
		pass_req_spec_char: 'Tener al menos un carácter especial',
		pass_req_not_account_name: 'No contener el nombre de la cuenta',
		pass_req_length: 'Tener al menos 8 caracteres',
		skip_mfa_check: 'Confíe en este dispositivo y no solicite el código MFA en los próximos 7 días',
		mult_fft_confirm: '¿Realmente desea solicitar una FFT para todos los sensores del controlador',
		mult_rebaseline_confirm: 'Realmente desea restablecer la línea base de todos los sensores en el controlador',
		mfa_warn_1: 'Mantenga su cuenta segura',
		mfa_warn_2: 'La autenticación de dos factores (2FA) será requerida para iniciar sesión a partir del 1 de octubre de 2025 para todos los usuarios con acceso de administrador de planta',
		mfa_warn_link: 'Configure 2FA hoy',		
		prodline_warn_1: 'Seleccione al menos una línea de producción notificable',
	  	creation_link_exp: 'El enlace para crear la contraseña ha expirado. Ingrese su correo electrónico a continuación y haga clic en enviar. <b>Recibirá un nuevo enlace en su bandeja de entrada en breve.</b>',
	  	to_clipboard_msg: 'El enlace fue copiado al portapapeles',
	  	mfa_warn_3: 'Si desea cambiar el número de teléfono, desactive 2FA o cámbielo a Authenticator',
	  	anomaly1: 'Anomalia de datos de metrica',
	  	api_secret_warn: 'Es la única vez que podrás ver el secreto',
	  	frequency_reset: 'La configuración de frecuencia se ha restablecido correctamente antes de guardar debido a que el método de lubricación ha cambiado. Configure los nuevos ajustes de frecuencia y guarde.',
		del_sensor: 'Eliminaste el sensor de la tarjeta de artículos',
	  	measurement_warn: 'Cambiar el tipo de medición a predeterminado',
	  	dt_cost_req_togr: 'Hora de inactividad/Hora y Horas Ahorradas deben completarse juntos',
	},

	constants: {
		'super_admin': 'Super Administrador',
		'plant_user': 'Usuario de Planta',
		'distributor': 'Distribuidor',
		'plant_admin': ' Administrador de Planta',
		'plant_superintendent': 'Gerente de Planta',
		'oee_proccess': 'Proceso de EGE',
		'corporate': 'Corporativo',
		'metric': 'Métrico',
		'imperial': 'Imperial',
		'pending': 'Pendiente',
		'approved': 'Aprobado',
		'completed': 'Completado',
		'success': 'Éxito',
		'fail': 'Fallo',
		unverified: 'No verificado',

		'humidity': 'Humedad',
		'temperature': 'Temperatura',
		'velocity': 'Velocidad',
		'high_frequency_acceleration': 'Aceleración de Alta Frecuencia',
		'fft': 'FFT',

		'warning': 'Aviso',
		'alarm': 'Alarma',
		'mixed': 'Mixtos',
		'lube': 'Lubricar',
		'good': 'Buena',
		'normal': 'Normal',
		'lubeline': 'Línea de lubricación',

		// -------------new-------------
		'high_zone': 'Zona alta',
		'low_zone': 'Zona baja',
		'high_alarm_zone': 'Zona de alarma alta',
		'low_alarm_zone': 'Zona de alarma baja',
		'off_alarm': 'Alarma apagada',
		'alarm_zone': 'Zona de alarma',
		'warning_zone': 'Zona de aviso',
		'lubeline_zone': 'Zona de lubricación',
		'baseline_zone': 'Zona de línea de base',
		'off_alarm_zone': 'Zona de Alarma Apagada',

		'motor': 'Motor',

		'jan': 'Ene',
		'feb': 'Feb',
		'mar': 'Mar',
		'apr': 'Abr',
		'may': 'May',
		'jun': 'Jun',
		'jul': 'Jul',
		'aug': 'Ago',
		'sept': 'Sep',
		'oct': 'Oct',
		'nov': 'Nov',
		'dec': 'Dic',

		'january': 'Enero',
		'february': 'Febrero',
		'march': 'Marzo',
		'april': 'Abril',
		'may_f': 'Mayo',
		'june': 'Junio',
		'july': 'Julio',
		'august': 'Agosto',
		'september': 'Septiembre',
		'october': 'Octubre',
		'november': 'Noviembre',
		'december': 'Diciembre',

		'monday': 'Lunes',
		'tuesday': 'Martes',
		'wednesday': 'Miércoles',
		'thursday': 'Jueves',
		'friday': 'Viernes',
		'satday': 'Sábado',
		'sunday': 'Domingo',

		// -----------New----------
		'acute': 'Agudo',
		'chronic': 'Crónico',
		'current': 'Corriente',
		'db_level': 'Nivel de dB',
		'pressure': 'Presión',
		'rpm': 'RPM',
		'motor_amperage': 'Amperaje del Motor',
		'x_acceleration': '(X) Aceleración',
		'y_acceleration': '(Y) Aceleración',
		'z_acceleration': '(Z) Aceleración',
		'x_velocity': '(X) Velocidad',
		'y_velocity': '(Y) Velocidad',
		'z_velocity': '(Z) Velocidad',
		'mm_sec': 'mm/seg',
		'x_displacement': '(X) Desplazamiento',
		'y_displacement': '(Y) Desplazamiento',
		'z_displacement': '(Z) Desplazamiento',
		'external_temperature': 'Temperatura Externa',
		'indoor_air_quality': 'Calidad del Aire Interior',
		'axial_velocity': 'Velocidad Axial',
		'axial_acceleration': 'Aceleración Axial',
		'radial_v_velocity': 'Velocidad (V) Radial',
		'radial_v_acceleration': 'Aceleración (V) Radial',
		'radial_h_velocity': 'Velocidad (H) Radial',
		'radial_h_acceleration': 'Aceleración (H) Radial',
		'mm_per_second': 'mm/s',
		'inches_per_second': 'pul/s',
		'celsius': 'Celsius',
		'fahrenheit': 'Fahrenheit',
		'g': 'g',
		'hertz': 'Hz',
		'dbuv': 'dB&micro;V',
		'amps': 'Amperes',
		'percent': '%',
		'psi': 'PSI',
		'iaq': 'IAQ',
		'mm': 'mm',
		'inches': 'pulgadas',
		'rebaseline': 'Restablecer la Línea de Base',
		'corrective_action': 'Acción Correctiva',
		'change_item': 'Change Item',
		'1_day': '1 Día',
		'7_days': '7 Días',
		'month': 'Mes',
		'custom_range': 'Rango personalizado',
		'banner': 'Banner',
		'ultrasound': 'Ultrasonido',
		'ultrasound_white_river': 'Ultrasonido White River',
		'banner_counter': 'Contador Banner',
		'ncd': 'NCD',
		'colortech_vfd_pressure_rpm_amps': 'RPM/AMP de presión VFD de Colortech',
		'pulsar': 'Pulsar',
		'perma': 'Perma',
		'battery': 'Battería',
		'line_powered': 'Alimentado por Línea',
		'graph': 'Gráfica',
		'dxm': 'DXM',
		'acknowledge_rebaseline': 'Reconocer línea de base',
		'controller': 'Controlador',
		'sensor_update_rebaseline': 'Restablecer la Línea de Base',
		'purchase_request': 'Solicitud de Compra',
		'service_request': 'Solicitud de Servicio',
		'same_value': 'Mismo Valor',
		'range': 'Rango',
		'numeric': 'Numérico',
		'percent_str': 'Por ciento',
		'in_work': 'Trabajando',
		'closed': 'Cerrado',
		'health_safety': 'Salud y Seguridad',
		'production_loss': 'Pérdida de Producción',
		'cost_reduction': 'Reducción de Costo',
		'future_opportunity': 'Oportunidad Futura',
		'refurbishment': 'Rehabilitación',
		'fabrication': 'Fabricación',
		'repair': 'Reparación',
		'weekly': 'Semanal',
		'monthly': 'Mensual',
		'yearly': 'Anual',
		'period_type': 'Tipo de Período',
		'period_dates': 'Fechas del Período',
		'overdue': 'Vencida',
		'today': 'Hoy',
		'this_week': 'Esta Semana',
		'this_month': 'Este Mes',
		'manual': 'Manual',
		'automatic': 'Automático',
		'item': 'Objeto',
		'nameplate': 'Placa',
		'plant': 'Planta',
		'master': 'Maestro',
		'auto': 'Automático',
		'work_break': 'Descanso laboral',
		'deviation': 'Desviación',
		'further_below_run_rate': 'Más por Debajo de la Tasa de Ejecución',
		'cell_modem': 'Módem Celular',
		'customer_connection': 'Conexión del Cliente',
		'base': 'Base',
		'advanced': 'Avanzado',
		'mail': 'Correo',
		'sms': 'Mensaje SMS',
		'on_hold': 'En Espera',
		'denied': 'Denegado',
		'all_in_one': 'Todo en uno',
		'cm1l': 'CM1L',
		'decibells': 'Decibeles',
		'extra_vibration': 'Vibración Extra',
		'custom_pdm_setup': 'Configuración Personalizada de PDM',
		'all_in_one_temp_vibe': 'Temperatura/Vibración Todo en uno',
		'wired_temp_vibe': 'Temperatura/Vibración Cableado',
		'temp_vibe_current': 'Corriente de Temperatura/Vibración',
		'environmental': 'Ambiental',
		'cm1l_sensor_custom_a': 'Sensor CM1L A personalizado',
		'ue_sensor': 'Sensor UE',
		'sdt_sensor_0_10v': 'Sensor SDT de 0-10V',
		'sdt_sensor_4_20ma': 'Sensor SDT de 4-20mA',
		'sdt_sensor_full_spectrum': 'Sensor SDT de Espectro Completo',
		'temperature_vibration': 'Temperatura Vibración',
		'ncd_sdt_full_spectrum_ultrasound': 'Ultrasonido de espectro completo NCD - SDT',
		'minute': 'Minuto',
		'hour': 'Hora',
		'day': 'Día',
		'lubricated': 'Lubricado',
		'empty': 'Vacío',
		'block': 'Bloqueo',
		'blocked': 'Bloqueado',
		'glitched': 'Fallado',
		'lubricator_error': 'Error del Lubricator',
		'lubricator_cartridge_empty': 'Cartucho del Lubricador Vacío',
		'lubricator_blocked': 'Lubricador Bloqueado',
		'lube_ok': 'Lubricador OK',
		'loss_connection': 'Pérdida de Conexión',
		'some_glitch': 'Alguna Falla',
		'unknown_status': 'Estado Desconocido',
		'gain_increase': 'Ganancia +',
		'gain_decrease': 'Ganancia -',
		'reset': 'Reestablecer',
		'proccess': 'Proceso',
		'yesterday': 'Ayer',
		'last_7_days': 'Últimos 7 días',
		'last_30_days': 'Últimos 30 días',
		'last_60_days': 'Últimos 60 días',
		'last_90_days': 'Últimos 90 días',
		'last_month': 'Último mes',
		'last_1_hour': 'Última hora',
		'last_3_hours': 'Últimas 3 horas',
		'last_12_hours': 'Últimas 12 horas',
		'ultrasound_sdt': 'Ultrasonido (SDT)',
		'usound': 'USound',
		'ultrasound_sdt_4_20': 'Ultrasonido (SDT 4-20)',
		'humidity_temperature': 'Humedad, Temperatura',
		'hum_temp': 'Hum/Temp',
		'vibe_temp': 'Vib/Temp',
		'temp_vibe': 'Temp/Vib',
		'vibration_temperature_current': 'Vibración, Temperatura, Corriente',
		'vibration_temperature': 'Vibración, Temperatura',
		'vibe_temp_curr': 'Vib/Temp/Corr',
		'custom_pdm': 'PDM Personalizado',
		'custom': 'Personalizado',
		'lubematrix': 'LubeMatrix',
		'lubematrix_sdt': 'LubeMatrix (SDT)',
		'lubematrix_sdt_4_20': 'LubeMatrix (SDT 4-20)',
		'lubematrix_sdt_full_spectrum': 'LubeMatrix (SDT de Espectro Completo)',
		'wired_vibration_temperature': 'Vibración, Temperatura Cableado',
		'ultrasound_sdt_full_spectrum': 'Ultrasonido (SDT de Espectro Completo)',
		'humidity_temperature_air_quality': 'Humedad, Temperatura, Calidad del Aire',
		'inches_sec': 'pulgadas/seg',
		'ncd_pressure': 'Presión de NCD',

		'year_to_date': 'Año hasta la fecha',
		'first_quarter': 'Primer trimestre',
		'second_quarter': 'Segundo trimestre',
		'third_quarter': 'Tercer trimestre',
		'fourth_quarter': 'Cuarto trimestre',
		last_1_month: 'Último mes',
		last_6_months: 'Últimos 6 meses',
		last_12_months: 'Últimos 12 meses',
		// ------------new------------
		'all_in_one_aa_battery': 'Todo en uno - Batería AA',
		'all_in_one_c_battery': 'Todo en uno - Batería C',
		'wired_aa_battery': 'Con cable - Batería AA',
		'wired_d_battery': 'Con cable - Batería D',
		'wired_stainless_steel_aa_battery': 'Con cable de acero inoxidable - Batería AA',
		'wired_stainless_steel_d_battery': 'Con cable de acero inoxidable - Batería D',
		'time_waveform_x': 'Forma de onda de tiempo (X)',
		'time_waveform_y': 'Forma de onda de tiempo (Y)',
		'time_waveform_z': 'Forma de onda de tiempo (Z)',
		'transformed_acceleration_x': 'Aceleración transformada (X)',
		'transformed_acceleration_y': 'Aceleración transformada (Y)',
		'transformed_acceleration_z': 'Aceleración transformada (Z)',
		'raw_acceleration_x': 'Aceleración bruta (X)',
		'raw_acceleration_y': 'Aceleración bruta (Y)',
		'raw_acceleration_z': 'Aceleración bruta (Z)',
		'velocity_x': 'Velocidad (X)',
		'velocity_y': 'Velocidad (Y)',
		'velocity_z': 'Velocidad (Z)',
		'cpm': 'CPM',

		'psig_0_50': 'PSIG 0-50',
		'psig_0_150': 'PSIG 0-150',
		'psis_0_500': 'PSIS 0-500',
		'psis_0_3000': 'PSIS 0-3000',
		'banner_temp_vibe_v2': 'Banner Temp Vibe V2',
		'time_domain_high_pass_buffer': 'Búfer de Paso Alto en el Dominio del Tiempo',
		'time_domain_high_frequency_enveloped':
			'Envolvente de Alta Frecuencia en el Dominio del Tiempo',
		'time_domain_low_pass_buffer': 'Búfer de Paso Bajo en el Dominio del Tiempo',
		'time_domain_full_band_buffer':
			'Búfer de Banda Completa en el Dominio del Tiempo',
		'offline': 'Desconectado',
		'lube_matrix_sdt_temp_c': 'Lube Matrix SDT Temp C',
		'lube_matrix_sdt_temp_f': 'Lube Matrix SDT Temp F',
		'ncd_custom_4_20': 'NCD Personalizado 4-20',
		'banner_v2_generic': 'Banner V2 Genérico',
		'banner_temp_vibe_V2_1': 'Banner Temp Vibe V2.1',
		'position_1': '1 Posición',
		'position_2': '2 Posiciones',
		'warning_alarm': 'Advertencia/Alarma',
		'low_high_alarms': 'Alarmas Bajas/Altas',
		'rsp_timeout': 'Tiempo de espera de RSP',
		'amplitude_alarm': 'Alarma de Amplitud',
		'controller_offline': 'Controlador Desconectado',
		'sensor_anomaly': 'Anomalía del Sensor',
		'graph_note': 'Nota de la Gráfica',

		'acute_warning': 'Advertencia Aguda',
		'acute_alarm': 'Alarma Aguda',
		'chronic_warning': 'Advertencia Crónica',
		'chronic_alarm': 'Alarma Crónica',
		'temperature_warning': 'Advertencia de Temperatura',
		'temperature_alarm': 'Alarma de Temperatura',
		'lube_alarm': 'Alarma de Lubricación',
		'low_alarm': 'Alarma Baja',
		'high_alarm': 'Alarma Alta',
		'other_warning': 'Otra Advertencia',
		'other_alarm': 'Otra Alarma',
		'sensor_offline': 'Sensor Desconectado',
		'battery_status': 'Estado de la Batería',
		'fft_alerts': 'Alertas FFT',
		'sensor_suspect_data': 'Datos Sospechosos del Sensor',
		'lube_matrix_alerts': 'Alertas de Lube Matrix',
		'oee_alerts': 'Alertas de OEE',

		new_requisition_added: 'Nueva Requisición Agregada',
		requisition_updated: 'Requisición Actualizada',
		requisition_approved: 'Requisición Aprobada',
		requisition_unapproved: 'Requisición Desaprobada',
		requisition_completed: 'Requisición Completada',
		requisition_denied: 'Requisición Denegada',
		requisition_deleted: 'Requisición Eliminada',
		'purpose': 'Propósito',
		'sensor_only': 'Solo Sensor',
		'hi_frequency_RMS_acceleration_magnitude': 'Magnitud de Aceleración RMS de Alta Frecuencia',
		'z_peak_acceleration': 'Aceleración Pico (Z)',
		'z_crest_factor': 'Factor de Cresta (Z)',
		'z_curtosis': 'Curtosis (Z)',
		'z_rms_velocity': 'Velocidad RMS (Z)',
		'y_rms_velocity': 'Velocidad RMS (Y)',
		'x_rms_velocity': 'Velocidad RMS (X)',
		'hi_frequency_rms_acceleration': 'Aceleración RMS de Alta Frecuencia',
		'z_hi_frequency_rms_acceleration': 'Aceleración RMS de Alta Frecuencia (Z)',
		'y_hi_frequency_rms_acceleration': 'Aceleración RMS de Alta Frecuencia (Y)',
		'x_hi_frequency_rms_acceleration': 'Aceleración RMS de Alta Frecuencia (X)',
		'max_peak_frequency': 'Frecuencia Pico Máxima',
		'max_peak_frequency_2nd': 'Frecuencia Pico Máxima (2da)',

		magnitude_xyz_hi_frequency_rms_acceleration: 'Magnitud (XYZ) RMS de Aceleración de Alta Frecuencia',
		magnitude_xyz_hi_frequency_pk_acceleration: 'Magnitud (XYZ) Aceleración Pico de Alta Frecuencia',
		magnitude_xyz_hi_frequency_crest_factor: 'Magnitud (XYZ) Factor de Cresta de Alta Frecuencia',
		magnitude_xyz_hi_frequency_kurtosis: 'Magnitud (XYZ) Curtosis de Alta Frecuencia',

		rms_velocity: 'Velocidad RMS',
		x_rms_velocity_mm: 'Velocidad RMS del Eje X (6-1000Hz)',
		y_rms_velocity_mm: 'Velocidad RMS del Eje Y (6-1000Hz)',
		z_rms_velocity_mm: 'Velocidad RMS del Eje Z (6-1000Hz)',

		magnitude_xyz_full_band_rms_acceleration: 'Magnitud (XYZ) RMS de Aceleración de Banda Completa',
		magnitude_xyz_full_band_pk_pk_acceleration: 'Magnitud (XYZ) Aceleración Pico a Pico de Banda Completa',
		max_peak_frequency_from_3_axis: 'Frecuencia Pico Máxima de los 3 Ejes',
		x_axis_peak_velocity_component_frequency: 'Frecuencia del Componente de Velocidad Pico del Eje X',
		y_axis_peak_velocity_component_frequency: 'Frecuencia del Componente de Velocidad Pico del Eje Y',
		z_axis_peak_velocity_component_frequency: 'Frecuencia del Componente de Velocidad Pico del Eje Z',

		x_axis_high_frequency_rms_acceleration: 'RMS de Aceleración de Alta Frecuencia del Eje X',
		y_axis_high_frequency_rms_acceleration: 'RMS de Aceleración de Alta Frecuencia del Eje Y',
		z_axis_high_frequency_rms_acceleration: 'RMS de Aceleración de Alta Frecuencia del Eje Z',

		x_axis_pk_acceleration: 'Aceleración Pico del Eje X',
		y_axis_pk_acceleration: 'Aceleración Pico del Eje Y',
		z_axis_pk_acceleration: 'Aceleración Pico del Eje Z',

		x_axis_crest_factor: 'Factor de Cresta del Eje X',
		y_axis_crest_factor: 'Factor de Cresta del Eje Y',
		z_axis_crest_factor: 'Factor de Cresta del Eje Z',

		x_axis_kurtosis: 'Curtosis del Eje X',
		y_axis_kurtosis: 'Curtosis del Eje Y',
		z_axis_kurtosis: 'Curtosis del Eje Z',

		x_axis_full_band_rms_acceleration_g: 'RMS de Aceleración de Banda Completa del Eje X',
		y_axis_full_band_rms_acceleration_g: 'RMS de Aceleración de Banda Completa del Eje Y',
		z_axis_full_band_rms_acceleration_g: 'RMS de Aceleración de Banda Completa del Eje Z',

		x_axis_full_band_pk_pk_acceleration_g: 'Aceleración Pico a Pico de Banda Completa del Eje X',
		y_axis_full_band_pk_pk_acceleration_g: 'Aceleración Pico a Pico de Banda Completa del Eje Y',
		z_axis_full_band_pk_pk_acceleration_g: 'Aceleración Pico a Pico de Banda Completa del Eje Z',

		x_axis_peak_acceleration_frequency_component: 'Frecuencia del Componente de Aceleración Pico del Eje X',
		y_axis_peak_acceleration_frequency_component: 'Frecuencia del Componente de Aceleración Pico del Eje Y',
		z_axis_peak_acceleration_frequency_component: 'Frecuencia del Componente de Aceleración Pico del Eje Z',

		hi_frequency_pk_acceleration: 'Aceleración Pico de Alta Frecuencia',
		hi_frequency_crest_factor: 'Factor de Cresta de Alta Frecuencia',
		hi_frequency_kurtosis: 'Curtosis de Alta Frecuencia',
		hi_frequency_full_band_rms_acceleration: 'Aceleración RMS de banda completa',
		hi_frequency_full_band_pk_pk_acceleration: 'Aceleración pico a pico de banda completa',
		hi_frequency_peak_acceleration_frequency_component: 'Frecuencia del Componente de Aceleración Pico de Alta Frecuencia',
		full_band_peak_acceleration_frequency_component: 'Frecuencia del Componente de Aceleración Pico de Banda Completa',
		external_input_rpm: 'RPM de Entrada Externa',
		external_input: 'Entrada Externa',
		linespeed_rpm: 'RPM de Velocidad de Línea',
		specification_rpm: 'RPM de Especificación',
		manual_rpm: 'RPM Manual',
		external: 'Externo',
		lube_v3: 'Lubricante V3',
		in_progress: 'En progreso',
		undefined: 'Indefinido',
		unit: 'Unidad',
		time_delta: 'Delta de Tiempo',
		ultrasound_high_frequency_impact_index: 'Índice de Impacto de Alta Frecuencia de Ultrasonido',
		ultrasound_high_frequency_peak_amplitude: 'Amplitud Pico de Alta Frecuencia de Ultrasonido',
		crest_factor: 'Factor de Cresta',
		kurtosis: 'Curtosis',
		ultrasound_rms: 'RMS de Ultrasonido',
		ultrasound_impact: 'Impacto de Ultrasonido',
		ultrasound_peak: 'Pico de Ultrasonido',
		ultrasound_crest_factor: 'Factor de Cresta de Ultrasonido',
		ultrasound_curtosis: 'Curtosis de Ultrasonido',
		high_frequency_rms_acceleration: 'Aceleración RMS de Alta Frecuencia',
		hfe_impact_index: 'Índice de Impacto HFE',
		high_frequency_pk_acceleration: 'Aceleración Pico de Alta Frecuencia',
		high_frequency_crest_factor: 'Factor de Cresta de Alta Frecuencia',
		high_frequency_kurtosis: 'Curtosis de Alta Frecuencia',
		full_band_rms_acceleration: 'Aceleración RMS de Banda Completa',
		full_band_peak_acceleration_frequency: 'Frecuencia de Aceleración Pico de Banda Completa',
		full_band_crest_factor: 'Factor de Cresta de Banda Completa',
		full_band_kurtosis: 'Curtosis de Banda Completa',
		peak_velocity_frequency_component: 'Componente de Frecuencia de Velocidad Pico',
		ultrasound_impact_index: 'Índice de Impacto de Ultrasonido',
		banner_m25: 'Banner M25',
		no_start_lubrication_command_response: 'No hay respuesta de comando de inicio de lubricación',
		no_lubrication_status_response: 'No hay respuesta de estado de lubricación',
		controller_timeout: 'Tiempo de espera del controlador',
		controller_error: 'Error del controlador',
		unsuccessful_shot: 'Disparo no exitoso',
		cycle_did_not_affect: 'El ciclo no afectó',
		shots_full_spent: 'Disparos completos gastados',
		lubrication_unlocked: 'Lubricación desbloqueada',
		compare: 'Comparar',
		standard_warning_alarm: 'Alarma/Advertencia',
		standard_low_high: 'Alto/Bajo',

		unlocked: 'Desbloqueado',
		no_fft_response: 'Sin respuesta FFT',
		node_offline: 'Nodo fuera de línea',
		unconfirmed_fft_request: 'Petición de FFT no confirmada',
		usg: 'USg',
	},

	short_name: {
		hi_freq_rms_accel: 'RMS Acel Alta Freq',
		ext_temp: 'Temp Ext',
		iaq: 'IAQ',
		hi_freq_accel: 'Acel Alta Freq',
		hi_freq_pk_accel: 'Acel Pico Alta Freq',
		hi_freq_crest_factor: 'Factor de Cresta Alta Freq',
		hi_freq_kurtosis: 'Curtosis Alta Freq',
		full_band_accel: 'Acel Banda Completa',
		full_band_pk_pk_accel: 'Acel Pico a Pico Banda Completa',
		x_rms_velocity: 'Veloc RMS X',
		y_rms_velocity: 'Veloc RMS Y',
		z_rms_velocity: 'Veloc RMS Z',
		peak_freq_3_axis: 'Freq Pico 3 Ejes',
		x_peak_vel_comp_freq: 'Freq Comp Vel Pico X',
		y_peak_vel_comp_freq: 'Freq Comp Vel Pico Y',
		z_peak_vel_comp_freq: 'Freq Comp Vel Pico Z',
		x_hi_freq_rms_accel: 'RMS Acel Alta Freq X',
		y_hi_freq_rms_accel: 'RMS Acel Alta Freq Y',
		z_hi_freq_rms_accel: 'RMS Acel Alta Freq Z',
		x_pk_accel: 'Acel Pico X',
		y_pk_accel: 'Acel Pico Y',
		z_pk_accel: 'Acel Pico Z',
		x_crest_factor: 'Factor de Cresta X',
		y_crest_factor: 'Factor de Cresta Y',
		z_crest_factor: 'Factor de Cresta Z',
		x_kurtosis: 'Curtosis X',
		y_kurtosis: 'Curtosis Y',
		z_kurtosis: 'Curtosis Z',
		x_full_band_rms_accel: 'RMS Acel Banda Comp X',
		y_full_band_rms_accel: 'RMS Acel Banda Comp Y',
		z_full_band_rms_accel: 'RMS Acel Banda Comp Z',
		x_full_band_pk_pk_accel: 'Acel Pico a Pico Banda Comp X',
		y_full_band_pk_pk_accel: 'Acel Pico a Pico Banda Comp Y',
		z_full_band_pk_pk_accel: 'Acel Pico a Pico Banda Comp Z',
		x_peak_accel_comp_freq: 'Freq Comp Acel Pico X',
		y_peak_accel_comp_freq: 'Freq Comp Acel Pico Y',
		z_peak_accel_comp_freq: 'Freq Comp Acel Pico Z',
		full_band_pk_accel_freq: 'Freq Acel Pico Banda Comp',
		peak_vel_comp_freq: 'Freq Comp Vel Pico',
	},

	technology: {
		vibration_temperature: 'Vibración, Temperatura',
		vibration_temperature_current: 'Vibración, Temperatura, Corriente',
		ultrasound: 'Ultrasonido',
		humidity_temperature: 'Humedad, Temperatura',
		custom: 'Personalizado',
		lube_matrix: 'LubeMatrix',
		humidity_temperature_air_quality: 'Humedad, Temperatura, Calidad del Aire',
		pressure: 'Presión',
		ultrasound_vibration_temperature: 'Ultrasonido, Vibración, Temperatura',
		uvt: 'UVT',
		manual_route: 'Ruta Manual',
	}
};
