export default {
	common: {
		select: 'Select',
		back: 'back',
		search: 'search',
		compare: 'compare',
		clear: 'clear',
		role: 'role',
		add: 'add',
		edit: 'edit',
		remove: 'remove',
		delete: 'delete',
		view: 'view',
		submit: 'submit',
		all: 'All',
		show: 'Show',
		hide: 'Hide',
		name: 'Name',
		showing: 'Showing',
		to: 'to',
		of: 'of',
		loading: 'loading',
		saving: 'saving',
		save: 'save',
		type: 'type',
		address: 'Address',
		mac_address: 'MAC Address',
		phone: 'Phone',
		info: 'Info',
		reconnect: 'Reconnect',
		offline: 'Offline',
		success: 'Success',
		time: 'Time',
		names: 'Names',
		last: 'Last',
		current: 'Current',
		yes: 'Yes',
		no: 'No',
		cancel: 'Cancel',
		every: 'Every',
		week: 'week',
		month: 'month',
		year: 'year',

		details: 'Details',
		details_pre: 'Details',
		description: 'description',
		period: 'Period',
		periodic: 'Periodic',
		operations: 'Operations',
		plant: 'plant',
		plants: 'plants',
		plant_s: 'plant(s)',
		production_line: 'Production line',
		line: 'Line', // production line
		production_lines: 'Production lines',
		prod_line: 'Prod. Line',
		utility: 'Utility',
		utilities: 'Utilities',
		machine: 'Machine',
		machines: 'Machines',
		asset: 'Asset',
		assets: 'Assets',
		item: 'Item',
		items: 'Items',
		work_order: 'Work Order',
		recurring_work_order: 'Recurring Work Order',
		work_orders: 'Work Orders',
		maintenance_log: 'Maintenance Log',
		maintenance_logs: 'Maintenance Logs',
		location: 'Location',
		locations: 'Locations',
		company: 'Company',
		companies: 'companies',
		controllers: 'Controllers',
		controller_s: 'Controller(s)',
		controller: 'Controller',
		sensors: 'Sensors',
		sensor: 'Sensor',
		sensor_s: 'Sensor(s)',
		teams: 'teams',
		team: 'team',
		users: 'users',
		user: 'user',
		creator: 'Creator',
		customer: 'Customer',
		technician: 'Technician',
		technicians: 'Technicians',
		region: 'Region',
		renewal_date: 'Renewal Date',
		im_csm: 'IM CSM',
		champions: 'Champions',
		distributors: 'distributors',
		distributor: 'distributor',
		vendors: 'vendors',
		vendor: 'vendor',
		requisition: 'requisition',
		requisitions: 'requisitions',
		task_procedures: 'task procedures',
		task_procedure: 'task procedure',
		work_order_type: 'work order type',
		work_order_types: 'work order types',
		work_stations: 'work stations',
		work_station: 'Work Station',
		brands: 'Brands',
		brand: 'Brand',
		part_numbers: 'Part Numbers',
		part_number: 'Part Number',
		model_number: 'Model Number',
		io_parameters: 'IO Parameters',
		item_types: 'item types',
		item_type: 'item type',
		categories: 'categories',
		category: 'category',
		applications: 'Applications',
		application: 'Application',
		storerooms: 'storerooms',
		storeroom: 'storeroom',
		storeroom_location: 'Storeroom location',
		location_on_plant: 'Location on plant',
		location_in_plant: 'Location in plant',
		location_on_machine: 'Location on machine',
		equipment_brand: 'Equipment Brand',
		equipment_brands: 'Equipment Brands',
		requisition_plant: 'Requisition Plant',
		lubematrix: 'Lubematrix',
		pdm: 'PDM',
		ncd: 'NCD',
		export: 'Export',
		cities: 'Cities',
		part: 'Part',
		main_dashboard: 'Main Dashboard',
		meeting_tracker: 'Meeting Tracker',
		roi_one_pager: 'ROI One Pager',
		roi_one_pagers: 'ROI One Pagers',
		customer_success_dashboard: 'Customer Success Dashboard',
		downtime: 'Downtime',
		lost: 'lost',
		minutes: 'minutes',
		seconds: 'seconds',
		min: 'min',
		action: 'Action',
		actions: 'Actions',
		file: 'file',
		image: 'image',
		images: 'images',
		roi: 'ROI',
		roi_final: 'ROI final',
		started_at: 'Started at',
		finished_at: 'Finished at',
		status: 'Status',
		attachments: 'Attachments',
		priod: 'Priod',
		frequency: 'Frequency',
		period_range: 'Period Range',
		period_dates: 'Period Dates',
		snooze: 'Snooze',
		parts: 'Parts',
		equipment: 'Equipment',
		equipments: 'Equipments',
		change: 'Change',
		task: 'task',
		close: 'Close',
		wo: 'WO',
		logs: 'Logs',
		today: 'Today',

		continue: 'Continue',
		assigned: 'Assigned',
		date: 'Date',
		expected_time: 'Expected Time',
		notes: 'Notes',
		quantity: 'Quantity',
		due_date: 'Due Date',
		due_this_week: 'Due this week',
		due_today: 'Due Today',
		late: 'Late',
		complete: 'Complete',
		created: 'Created',
		create: 'Create',
		denied: 'Denied',
		approve: 'Approve',
		solved: 'Solved',
		hours: 'Hours',
		sec: 'sec',
		budget: 'Budget',
		budget_cost: 'Budget Cost',
		fab_shop_budget: 'Fab Shop Budget',
		running_total: 'Running Total',
		time_left: 'Time left',
		graph: 'Graph',
		breakdown_machines: 'Breakdown Machines',
		day: 'Day',
		days: 'Days',
		afternoon: 'Afternoon',
		night: 'Night',
		breakdown: 'Breakdown',
		shift: 'shift',
		unlock: 'UNLOCK',
		print: 'Print',
		start: 'Start',
		finish: 'Finish',
		id: 'ID',
		log: 'Log',
		files: 'Files',
		unapprove: 'Unapprove',
		on_hold: 'On Hold',
		off_hold: 'Off Hold',
		po: 'PO', //should be same
		apply: 'apply',
		calculate: 'calculate',
		comments: 'Comments',
		comment: 'Comment',
		main: 'Main',
		menu: 'Menu',
		sso: 'SSO',
		saml: 'SAML',
		enable: 'Enable',
		move: 'Move',
		quote: 'Quote',
		service: 'Service',
		crossover: 'Crossover',
		specifications: 'Specifications',
		history: 'History',
		specs: 'Specs',
		pdm_item: 'PDM Item',
		pdm_items: 'PDM Items',
		threshold: 'Threshold',
		thresholds: 'Thresholds',
		reset: 'Reset',
		for: 'for',
		download: 'download',
		axis: 'Axis',
		params: 'Params',
		split: 'Split',
		// --------------new--------------
		send: 'Send',
		enter: 'Enter',
		disable: 'Disable',
		disabled: 'Disabled',
		performed: 'Performed',
		downloaded: 'downloaded',
		process: 'Process',
		processes: 'Processes',
		processing: 'Processing',
		working: 'Working',
		pump: 'Pump',
		pumps: 'Pumps',
		node: 'Node',
		radio_node: 'Radio node',
		radio_nodes: 'Radio nodes',
		fft: 'FFT',
		ffts: 'FFTs',
		error: 'Error',
		errors: 'Errors',
		fault: 'Fault',
		faults: 'Faults',
		import_log: 'Import Log',
		import_logs: 'Import Logs',
		back_end_Register: 'Back-End Register',
		back_end_Registers: 'Back-End Registers',
		custom_formula: 'Custom Formula',
		custom_formulas: 'Custom Formulas',
		email_template: 'Email Template',
		email_templates: 'Email Templates',
		industrial_service: 'Industrial Service',
		industrial_services: 'Industrial Services',
		lube_type: 'Lube Type',
		lube_types: 'Lube Types',
		in_system: 'In System',
		authorization: 'Authorization',
		new: 'new',
		with: 'with',
		chart: 'Chart',
		capacity: 'capacity',
		data: 'data',
		go: 'Go',
		warnings: 'Warnings',
		templates: 'Templates',
		page: 'Page',
		gain: 'Gain',
		toggle: 'Toggle',
		on: 'On',
		off: 'Off',
		high_speed: 'High speed',
		purge_mode: 'Purge Mode',
		trigger: 'Trigger',
		lube_cycle: 'Lube Cycle',
		cycle: 'cycle',
		lubrication: 'Lubrication',
		stop: 'Stop',
		stopped: 'stopped',
		started: 'started',
		has: 'has',
		increase: 'Increase',
		decrease: 'Decrease',
		end: 'End',
		external_sensor: 'External Sensor',
		count: 'Count',
		input: 'input',
		value: 'value',
		values: 'values',
		entity: 'entity',
		example: 'example',
		number: 'number',
		system: 'system',
		time_zone: 'Time zone',
		method: 'method',
		code: 'Code',
		router_number: 'Router number',
		version: 'Version',
		report: 'Report',
		reports: 'Reports',
		personal: 'Personal',
		port: 'Port',
		expression: 'Expression',
		dataset: 'Dataset',
		rpm: 'RPM',
		rating: 'Rating',
		position: 'Position',
		setup: 'Setup',
		scope: 'Scope',
		last_name: 'Last name',
		typing: 'typing',
		minus: 'minus',
		plus: 'plus',
		predefined: 'Predefined',
		title: 'Title',
		key: 'key',
		confirm: 'Confirm',
		admins: 'Admins',
		stage: 'Stage',
		timerange: 'time range',
		cost: 'Cost',
		material: 'Material',
		rate: 'Rate',
		pack: 'Pack',
		mode: 'Mode',
		cartridge: 'Cartridge',
		amount: 'Amount',
		bearing: 'Bearing',
		parameters: 'Parameters',
		parameter: 'Parameter',
		rules: 'Rules',
		alert: 'Alert',
		comparison: 'Comparison',
		graco_pump: 'Graco-pump',
		language: 'Language',
		media: 'Media',
		option: 'Option',
		predefined_value: 'Predefined Value',
		predefined_values: 'Predefined Values',
		is_rpm: 'Is RPM',
		is_fla: 'Is FLA',
		run_rate: 'Run Rate',
		stop_time: 'Stop Time',
		work_days: 'Work days',
		work_time: 'Work time',
		breaktime: 'Breaktime',
		cofigure: 'Cofigure',
		script: 'Script',
		login: 'Login',
		logout: 'Logout',
		city: 'City',
		state: 'State',
		country: 'Country',
		drive_type: 'Drive Type',
		custom: 'Custom',
		field: 'Field',
		fields: 'Fields',
		supervisor: 'Supervisor',
		logo: 'Logo',
		measurement: 'Measurement',
		billing_plan: 'Billing Plan',
		email_list: 'Email List',
		contact: 'Contact',
		email: 'Email',
		one_click: 'one click',
		for_buy: 'for buy',
		for_service: 'for service',
		equipment_types: 'Equipment types',
		break_time: 'Break time',
		origin_type: 'Origin type',
		loss_count: 'Loss count',
		max: 'max',
		solenoids: 'Solenoids',
		fab_plant: 'Fab Plant',
		work_type: 'Work Type',
		materials: 'Materials',
		additional: 'Additional',
		tracking: 'Tracking',
		shipping: 'Shipping',
		note: 'Note',
		periods: 'Periods',
		months: 'Months',
		recommended: 'Recommended',
		rebaseline: 'Rebaseline',
		archive: 'Archive',
		power: 'Power',
		vertical: 'Vertical',
		horizontal: 'Horizontal',
		axial: 'Axial',
		lubricator: 'Lubricator',
		configuration: 'Configuration',
		information: 'Information',
		grease_pack: 'Grease pack',
		density: 'Density',
		lubricant: 'Lubricant',
		level: 'Level',
		replenishment: 'Replenishment',
		lube_sets: 'Lube Sets',
		lube_cycles: 'Lube Cycles',
		starting_at: 'Starting At',
		data_set: 'Data Set',
		register: 'Register',
		vibration: 'Vibration',
		password: 'Password',
		notifications: 'Notifications',
		sms: 'SMS',
		push: 'Push',
		request: 'Request',
		type_options: 'TYPE OPTIONS',
		total: 'total',
		money: 'Money',
		actual_cost: 'Actual Cost',
		low_limit: 'Low Limit',
		high_limit: 'High Limit',
		deadband: 'Deadband',
		re_baseline: 'Re-baseline',
		successfull: 'Successfull',
		successfully: 'Successfully',
		requesting: 'Requesting',
		deny: 'Deny',
		requested_completion: 'Requested Completion',
		requestor: 'Requestor',
		requestor_plant: 'Requestor Plant',
		equipment_details: 'Equipment Details',
		plant_name: 'Plant Name',
		reconnection: 'Reconnection',
		reboot: 'Reboot',
		convert: 'Convert',
		reject: 'Reject',
		redirect: 'Redirect',
		archived: 'Archived',
		restored: 'Restored',
		analogues: 'Analogues',
		alarms: 'Alarms',
		alarm: 'Alarm',
		width: 'Width',
		stock_quantity: 'Stock Quantity',
		contact_name: 'Contact name',
		date_time: 'Date time',
		date_sent: 'Date Sent',
		requested_date: 'Requested Date',
		estimated_start_date: 'Estimated Start Date',
		estimated_completion_date: 'Estimated Completion Date',
		machine_name: 'Machine Name',
		no_name: 'No Name',
		asset_number: 'Asset Number',
		graphs: 'Graphs',
		sensor_type: 'Sensor Type',
		battery_charge: 'Battery Charge',
		connection_strength: 'Connection Strength',
		type_of_equipment: 'Type of equipment',
		alert_rule: 'Alert rule',
		sensor_equipment: 'Sensor equipment',
		submitted: 'Submitted',
		wo_request: 'WO Request',
		statistics: 'Statistics',
		option_values: 'Option values',
		media_values: 'Media values',
		formulas: 'Formulas',
		formula: 'Formula',
		options: 'Options',
		billing_plan_cost: 'Billing Plan Cost',
		form: 'Form',
		recurring_work_orders: 'Recurring Work Orders',
		filter: 'Filter',
		sender: 'Sender',
		full_name: 'Full name',
		drive: 'Drive',
		site: 'Site',
		without: 'Without',
		fab_shop_manager: 'Fab Shop Manager',
		requisitioner: 'Requisitioner',
		warning: 'Warning',
		order: 'Order',
		change_by: 'Change by',
		displacement: 'Displacement',
		zone: 'Zone',
		zones: 'Zones',
		side: 'Side',
		ring_direct: 'Ring/Direct',
		bearings: 'Bearings',
		meeting_trackers: 'Meeting Trackers',
		types: 'Types',
		fab: 'Fab',
		work_order_request: 'Work Order Request',
		work_order_requests: 'Work Order Requests',
		text: 'text',
		price: 'Price',
		libraries: 'Libraries',
		prodlines: 'ProdLines',
		range: 'Range',
		hello: 'Hello',

		// --------------new--------------
		testing: 'Testing',
		tresholds: 'Tresholds',
		acceleration: 'Acceleration',
		velocity: 'Velocity',

		pm: 'PM',
		reason: 'Reason',
		none: 'None',
		hour: 'hour',

		parent: 'Parent',
		services: 'Services',

		runtime: 'Runtime',
		last_reset: 'Last Reset',
		industrial_matrix: 'Industrial Matrix',
		permission: 'Permission',
		permissions: 'Permissions',
		viewing: 'viewing',
		creating: 'creating',
		updating: 'updating',
		updated: 'updated',
		deleting: 'deleting',
		section: 'Section',
		roles: 'Roles',
		child_roles: 'Child Roles',
		device: 'Device',
		fmax: 'Fmax',
		amplitude: 'Amplitude',
		notification: 'Notification',
		units: 'Units',
		linespeed: 'Linespeed',
		overlay: 'Overlay',
		command: 'Command',
		commands: 'Commands',
		response: 'Response',
		is_empty: 'is empty',
		standard: 'Standard',
		envelope: 'Envelope',
		cursor: 'Cursor',
		cursors: 'Cursors',
		peaks: 'Peaks',
		step: 'Step',
		steps: 'Steps',
		waterfall: 'Waterfall',
		radio: 'Radio',
		retry: 'Retry',
		rotate: 'Rotate',
		rotation: 'Rotation',
		zoom: 'Zoom',
		drag: 'Drag',
		subtype: 'Subtype',
		commissioning: 'Commissioning',
		default: 'Default',
		archiving: 'archiving',
		customizable: 'Customizable',
		signed: 'Signed',
		speed: 'Speed',
		source: 'Source',
		exteranal: 'Exteranal',
		specification: 'Specification',
		the: 'The',
		serial_number: 'Serial Number',
		model: 'Model',
		firmware_number: 'Firmware Number',
		force_mfa: 'Force MFA',
		old: 'Old',
		authenticator: 'Authenticator',
		allow: 'Allow',
		unknown: 'Unknown',
		overall: 'Overall',
		summaries: 'Summaries',
		in_service: 'In Service',
		overall_program_review: 'Overall Program Review',
		multi_view: 'Multi-View',
		launch_time: 'Launch Time',
		days_range: 'Days Range',
		manually: 'Manually',
		baselining: 'Baselining',
		share: 'Share',
		column: 'Column',
		tag: 'Tag',
		fail: 'Fail',
		low: 'Low',
		high: 'High',
		areaspline: 'Areaspline',
		luber: 'Luber',
		favorites: 'Favorites',
		analysis: 'Analysis',
		vibration_analysis: 'Vibration Analysis',
		unit: 'Unit',
		crossover_tags: 'Crossover Tags',
		child: 'Child',
		childs: 'Childs',
		component: 'Component',
		components: 'Components',
		harmonics: 'Harmonics',
		editable: 'Editable',
		difference: 'Difference',
	},

	sidebar_menu: {
		predictive_maintenance: 'Predictive Maintenance',
		dashboard: 'Dashboard',
		customer_success: 'Customer Success',
		oee: 'OEE',
		system: 'system',
		profile: 'profile',
		rnd: 'rnd',
		settings: 'settings',
		cmms: 'CMMS',
		work_orders_maintenance_logs: 'Work orders & maintenance logs',
		roi_calculator: 'ROI calculator',
		work_order_requests: 'work order requests',
		misc_parts: 'misc parts',
		work_order_import: 'work order import',
		import: 'import',
		plant_import: 'plant import',
		plant_import_logs: 'plant import logs',
		master_import: 'master import',
		asset_management: 'asset management',
		library: 'library',
		work_stations: 'Work Stations',
		categories: 'Categories',
		cost_savings_calculator: 'Cost savings calculator',
		user_roles: 'User Roles',
		user_role: 'User Role',
		import_master: 'import master',
		item_types_categories: 'Item types categories',
		users_teams: 'Users teams',
		corporate_view: 'Corporate View',
	},

	phrases: {
		low_cut_filter: 'Low Cut Filter',
		high_cut_filter: 'High Cut Filter',
		model_power: 'Model/Power',
		// --------------new 2--------------
		start_date: 'Start date',
		end_date: 'End date',
		modes_of_cycles: 'Modes of Cycles',
		percentage_of_points_above_alarm: 'Percentage of points above alarm',
		cool_down_time_minutes: 'Cool down time (minutes)',
		warm_up_time_minutes: 'Warm up time (minutes)',
		scheduled_start_date_and_time_required: 'Scheduled start date and time required',
		add_new_note_to_point: 'Add new note to point',
		unable_to_verify_lube_cycle: 'Unable to Verify Lube Cycle',
		gain_adjustment_failure: 'Gain adjustment failure',
		sensor_gain_increased: 'Sensor gain Increased',
		sensor_gain_decreased: 'Sensor gain Decreased',
		sensor_gain_reset: 'Sensor gain Reset',
		gain_adjustment_controller_timeout: 'Gain adjustment controller timeout',
		see_maintenance_log: 'See Maintenance Log',
		to_be_discussed: 'To be discussed',
		you_are_not_authorized_to_view_this_page:
			'You are not authorized to view this page',
		you_do_not_have_permissions_to_view_this_page:
			'You do not have permissions to view this page',
		limited_access: 'Limited access',
		not_authorized: 'Not authorized',
		try_sign_in_again: 'Try sign in again',
		load_more: 'Load more',
		create_item_first: 'Create Item first',
		equipment_name: 'Equipment Name',
		expected_time: 'Expected Time',
		radio_node_position: 'Radio node position',
		additional_details: 'Additional Details',
		// --------------new--------------
		mismatch_in_sensor_type_please_check_configuration:
			'Mismatch in sensor type, please check configuration',
		roi_final_should_be_a_number: 'ROI Final should be a Number',
		file_is_required: 'File is required',
		selection_out_of_chart_range: 'Selection out of chart range',
		you_do_not_have_permissions_to_save: 'You do not have permissions to save',
		restricted_actions: 'Restricted actions',
		choose_a_different_axis: 'Choose a different axis',
		working_config: 'Working Config',
		ncd_config_saved_successfully: 'NCD config saved Successfully',
		gain_adjustment_successful: 'Gain Adjustment Successful',
		gain_adjustment_failed: 'Gain Adjustment Failed',
		controller_timeout: 'Controller Timeout',
		command_sent_successfully: 'Command Sent Successfully',
		doesn_t_exists: "doesn't exists",
		error_check_controller_connectivity: 'Error - Check Controller Connectivity',
		sensor_created_successfully: 'Sensor Created Successfully',
		web_socket_error: 'Web Socket Error',
		should_be_assigned: 'should be assigned',
		data_isn_t_ready: "Data isn't ready",
		total_time_should_be_15_minutes: 'Total time should be 15+ minutes',
		is_required: 'is required',
		check_form_fields: 'Check form fields',
		validation_error: 'Validation error',
		reverting_attempt_unsuccessfull: 'Reverting Attempt Unsuccessfull',
		view_line_details: 'View Line Details',
		disable_off_alarm: 'Disable Off-Alarm',
		reject_this_work_order_request: 'Reject this Work Order Request',
		see_work_order_request: 'See Work Order Request',
		apply_this_action_to_all_reccurring_orders_or_only_this_one:
			'Apply this action to all reccurring orders or only this one',
		close_this_work_order: 'Close this Work Order',
		this_will_complete_selected_workOrders: 'This will complete selected WorkOrders',
		this_will_permanently_delete_selected: 'This will permanently delete selected',
		this_will_permanently_delete_current: 'This will permanently delete current',
		clear_logs: 'Clear logs',
		new_configure: 'New Configure',
		new_script: 'New Script',
		do_this_action_for: 'Do this action for',
		delete_this_option: 'Delete this Option',
		expected_receive_date: 'Expected Receive Date',
		shipping_method: 'Shipping Method',
		reject_reason: 'Reject Reason',
		additional_work_order_details: 'Additional Work Order Details',
		site_visit_required: 'Site Visit Required?',
		do_you_want_to_specify_shipping_details:
			'Do you want to specify Shipping Details',
		this_order: 'this order',
		delete_this_requisition: 'Delete this Requisition',
		delete_this_activity: 'Delete this activity',
		check_controller_connectivity: 'Check Controller Connectivity',
		rebase_line_by_selected_range: 'Rebase Line by selected range',
		import_log_is_empty: 'Import log is empty',
		low_pass_filter: 'Low Pass Filter',
		high_pass_filter: 'High Pass Filter',
		enable_filtering: 'Enable Filtering',
		sample_duration: 'Sample Duration',
		output_data_rate: 'Output Data Rate',
		frequency_range: 'Frequency Range',
		sensor_boot_time: 'Sensor Boot Time',
		connection_strength_trend: 'Connection Strength Trend',
		connection_strength_average: 'Connection Strength Average',
		view_graph: 'View Graph',
		custom_level_alarm: 'Custom Level Alarm',
		critical_alarm: 'Critical Alarm',
		adding_notes_notifications: 'Adding Notes Notifications',
		email_notifications: 'Email Notifications',
		daily_summary_sensor_notifications: 'Daily Summary Sensor Notifications',
		real_time_sensor_notifications: 'Real Time Sensor Notifications',
		daily_summary_notify_at: 'Daily summary notify at',
		daily_summary: 'Daily summary',
		hourly_rate: 'Hourly Rate',
		is_receive_sensors_anomaly_notifications:
			'Is receive sensors anomaly notifications',
		notifiable_plants: 'Notifiable plants',
		first_name: 'First name',
		last_name: 'Last name',
		actual_lubricant_per_cycle: 'Actual Lubricant Per Cycle',
		lubricant_dilevered_per_cycle: 'Lubricant Dilevered Per Cycle',
		target_lubricant_per_cycle: 'Target Lubricant Per Cycle',
		total_lubricant_dilevered_in_all_sets: 'Total Lubricant Dilevered In All Sets',
		lube_cycle_dwell_time: 'Lube Cycle Dwell Time',
		time_between_lube_sets_sec: 'Time Between Lube Sets (sec)',
		time_between_lube_cycles_sec: 'Time Between Lube Cycles (sec)',
		lube_cycles_per_set: 'Lube Cycles Per Set',
		calculated_lube_sets: 'Calculated Lube Sets',
		calculated_time: 'Calculated Time',
		calculated_cycles_per_set: 'Calculated Cycles Per Set',
		apply_calculated_data: 'Apply calculated data',
		lube_logic_setup: 'Lube Logic Setup',
		target_lubricant_per_set: 'Target Lubricant Per Set',
		lubricant_delivered_per_set: 'Lubricant Delivered Per Set',
		actual_lubricant_per_set: 'Actual Lubricant Per Set',
		total_lubricant_delivered_in_all_sets: 'Total Lubricant Delivered In All Sets',
		lube_cycles_per_cartridge: 'Lube Cycles Per Cartridge',
		lube_cycle_spent_count: 'Lube Cycle Spent Count',
		calculated_lubricated_quantity: 'Calculated Lubricated Quantity',
		outside_diameter: 'Outside Diameter',
		hide_vertical_axis_rms: 'Hide Vertical Axis RMS',
		reason_denied: 'Reason Denied',
		see_visit_required: 'See Visit Required?',
		notifications_for: 'Notifications for',
		industrial_services: 'Industrial Services',
		equipment_breakdown: 'Equipment Breakdown',
		installed_at: 'Installed at',
		without_brand: 'Without Brand',
		extended_work_date: 'Extended Work Date',
		stop_time_tooltip:
			'This is when the count received are 0s and needs to be triggered by how many 0 reads we receive in a row',
		further_below_run_rate_tooltip:
			'This is an accumulated average of a slow down where an additional deviation was detected beyond the overall average of the original slowdown',
		acute_samples: 'Acute samples',
		stable_samples: 'Stable samples',
		samples_to_alarm: 'Samples to Alarm',
		samples_to_settle: 'Samples to Settle',
		commucate_method: 'Commucate method',
		connection_type: 'Connection Type',
		binding_code: 'Binding Code',
		cloud_connection_type: 'Cloud Connection Type',
		router_sim_card_number: 'Router SIM Card Number',
		router_serial_number: 'Router Serial Number',
		measuring_system: 'Measuring system',
		azure_ad_identifier: 'Azure AD Identifier',
		move_to: 'Move To',
		type_option_values: 'Type option values',
		type_media_values: 'Type media values',
		further_below_run_rate_percent: 'Further Below Run Rate (percent)',
		crossover_exluded: 'Crossover exluded',
		no_file_loaded: 'No file loaded',
		add_to_completed_this_week: 'Add to Completed this week',
		add_to_recommended_actions: 'Add to Recommended Actions',
		add_to_activities_planned_for_next_week_period:
			'Add to Activities planned for next week/period',
		type_of_equipments: 'Type of Equipments',
		site_visit: 'Site visit',
		select_equipment_whose_order_you_want_to_reset:
			'Select equipment whose order you want to reset',
		whose_order_you_want: 'whose order you want',
		convert_to_predefined: 'Convert to predefined',
		show_in_filter: 'Show in filter',
		show_in_item: 'Show in item',
		show_in_analysis: 'Show in analysis',
		crossover_rule_type: 'Crossover Rule Type',
		sensor_parameter: 'Sensor parameter',
		for_incoming_registers: 'For incoming registers',
		reverse_formula: 'Reverse formula',
		click_to_upload: 'Click to upload',
		upload_file: 'Upload file',
		the_sensor_gain: 'The Sensor Gain',
		manual_lubrication_command_sent: 'Manual Lubrication command sent',
		purge_mode_is: 'Purge Mode is', // on/off
		requisition_form: 'Requisition Form',
		spectrum_analysis: 'Spectrum Analysis',
		plant_dashboard: 'Plant Dashboard',
		existing_sensors: 'Existing sensors',
		group_data_by: 'Group data by',
		loss_count: 'Loss count',
		accumulative_downtime: 'Accumulative Downtime',
		maximum_capacity: 'Maximum capacity',
		realistic_capacity: 'Realistic capacity',
		import_process_funished_successfully: 'Import process funished successfully',
		loaded_results_from_file: 'Loaded results from file',
		machine_without_name: 'Machine without name',
		reset_sensor: 'Reset sensor',
		gain_signal_value: 'Gain signal value',
		extra_vibration_threshold_multipliers: 'Extra vibration threshold multipliers',
		alarm_zone_should_be_higher_than_warning_zone:
			'Alarm zone should be higher than Warning zone',
		all_threshold_multipliers_fields_should_have_values:
			'All threshold multipliers fields should have values',
		fft_locked_out_remaining_time: 'FFT Locked Out - Remaining Time',
		// --------------------------------
		thresholds_re_baseline: 'Thresholds re-baseline',
		it_will_take_some_time: 'It will take some time',
		request_fft: 'Request FFT',
		last_fft: 'Last FFT',
		charts_loading: 'Charts loading',
		there_are: 'There are',
		no_charts: 'no charts',
		no_statistics: 'no statistics',
		for_this_sensor: 'for this sensor',
		show_all: 'Show All',
		production_line_without_name: 'Production Line without name',
		edit_machine: 'Edit Machine',
		production_line_details: 'Production Line details',
		quote_send: 'Quote send',
		there_are_no_vendors_for_request_selected:
			'There are no vendors for request selected',
		one_click_request: 'One Click Request',
		loc_on_machine: 'Loc on machine',
		motor_results: 'Motor Results',
		view_all: 'View All',
		request_for_quotation: 'Request for Quotation',
		request_for_quotations: 'Request for Quotations',
		data_missing_for_crossovers: 'Data Missing For Crossovers',
		this_asset_has_not_equipments: 'This asset has not equipments',
		reply_url_claims_service_url: 'Reply URL (Claims Service URL)',
		identifier_object_id: 'Identifier (object ID)',
		paste_parameters_from_azure_and_click_button_save:
			'Paste parameters from Azure and click button “Save”',
		section_enter_the_following_information:
			'section, enter the following information',
		basic_saml_configuration: 'Basic SAML Configuration',
		create_a_new_non_gallery_app: 'create a new non-gallery app',
		add_industrialmatrix_to_azure_ad: 'Add IndustrialMatrix to Azure AD',
		open_your_azure_ad_administrator_account_and:
			'Open your Azure AD administrator account and',
		for_the_new_application: 'For the new application',
		requisition_plant_dashboard: 'Requisition Plant Dashboard',
		fab_plant_dashboard: 'Fab Plant Dashboard',
		work_order_company_overview: 'Work Order Company Overview',
		repair_cost_avoidance: 'Repair Cost Avoidance',
		contractor_markup: 'Contractor Markup',
		contractor_hourly_rate: 'Contractor hourly rate',
		dt_per_hour: 'Down Time/Hour',
		hours_saved_or_lead_time: 'Hours Saved / Lead Time',
		contractor_quote: 'Contractor Quote',
		
		tech_hours: 'Tech Hours',
		date_selection: 'Date Selection',
		date_sent: 'Date Sent',
		requested_date: 'Requested Date',
		estimated_start_date: 'Estimated Start Date',
		estimated_completion_date: 'Estimated Completion Date',
		has_not_statistics_for_this_range: 'Has not Statistics for this range',
		select_shift: 'Select shift',
		edit_work_order: 'Edit Work Order',
		work_order_details: 'Work Order Details',
		create_work_order_request: 'CREATE WORK ORDER REQUEST',
		maintenance_log_details: 'Maintenance Log Details',
		supervisor_notes: 'Supervisor notes',
		acknowledge_by_supervisor: 'Acknowledge by supervisor',
		sanitization_of_tools: 'Sanitization of Tools',
		problem_solved: 'Problem Solved',
		top_5_breakdowns: 'TOP 5 BREAKDOWNS',
		to_view_the_information_of_the_work_order_click_on_the_preview_button_from_the_list_of_work_orders:
			'To view the information of the work order, click on the preview button from the list of work orders',
		open_details: 'Open Details',
		this_will_set_in_work_status_to_selected_workorders:
			'This will set In Work status to selected WorkOrders',
		this_will_complete_selected_workorders: 'This will complete selected WorkOrders',
		this_will_close_selected_workorders: 'This will close selected WorkOrders',
		creation_is_not_allowed: 'Creation is not allowed',
		wo_name: 'WO Name',
		required_items: 'Required items',
		in_work: 'In Work',
		from_request: 'From Request',
		assigned_to_me: 'Assigned to me',
		change_status: 'Change Status',
		assigned_to: 'Assigned to',
		create_work_order_type: 'Create Work Order Type',
		please_check_fields_errors_first: 'Please check fields errors first',
		Apply_this_action_to_all_reccurring_orders_or_only_this_one:
			'Apply this action to all reccurring orders or only this one',
		to_all: 'To all',
		only_this_one: 'Only this one',
		create_part: 'Create Part',
		technician_users: 'Technician Users',
		teams_in_the_plant: 'Teams in the plant',
		at_least_one_of_these_fields_is_required:
			'At least one of these fields is required',
		show_procedures: 'Show procedures',
		parts_from_procedure: 'Parts from procedure',
		snooze_alerts: 'Snooze Alerts',
		upload_files: 'Upload files',
		work_order_name: 'Work Order Name',
		select_date: 'Select date',
		statistics_for_period: 'Statistics for period',
		select_plant_first: 'Select plant first',
		select_company_first: 'Select Company first',
		choose_plant_first: 'Choose plant first',
		data_driven_recommended_actions: 'Data Driven Recommended Actions',
		data_driven_issues_resolved: 'Data Driven Issues Resolved',
		last_3_months: 'Last 3 months',
		ydt: 'YDT',
		last_12_months: 'Last 12 months',
		overall_asset_health: 'Overall Asset Health',
		roi_value_creation: 'ROI/Value Creation',
		no_data: 'NO DATA',
		create_work_order: 'Create Work Order',
		view_machines: 'View Machines',
		show_binding_machines: 'Show Binding Machines',
		edit_line: 'Edit Line',
		asset_without_name: 'Asset without name',
		part_number_without_name: 'Part Number without name',
		not_found: 'Not Found',
		show_binding_items: 'Show Binding Items',
		move_to_storeroom: 'Move To Storeroom',
		move_item: 'Move Item',
		equipments_count: 'Equipments count',
		models_count: 'Models count',
		view_sensors: 'View Sensors',
		edit_item: 'Edit Item',
		lube_cycle_was_reset: 'Lube Cycle was Reset',
		spent_shots_was_reset: 'Spent Shots was Reset',
		grease_pack_was_reset: 'Grease pack was Reset',
		reset_cycle: 'Reset Cycle',
		clear_filters: 'Clear filters',
		display_archived_sensors: 'Display Archived Sensors',
		issues_detected: 'Issues Detected',
		issues_resolved: 'Issues Resolved',
		lube_delivered: 'Lube Delivered',
		lube_cycles_auto: 'Lube Cycles Auto',
		unsuccessful_autolube: 'Unsuccessful Autolube',
		autolube_alarm: 'Autolube Alarm',
		lube_cycles_manual: 'Lube Cycles Manual',
		automatic_ffts_generated: 'Automatic FFT’s Generated',
		reset_lube: 'Reset Lube',
		luber_empty: 'Luber Empty',
		reset_grease_pack: 'Reset Grease Pack',
		sensor_statistics: 'Sensor Statistics',
		add_to_compare_list: 'Add to compare list',
		all_storerooms: 'All storerooms',
		all_storeroom_locations: 'All storeroom locations',
		select_alert_types: 'Select alert types',
		show_binding_assets: 'Show Binding Assets',
		all_statistics: 'All Statistics',
		asset_health_score: 'Asset Health Score',
		time_in: 'Time in',
		to_do: 'TO DO',
		sensors_offline: 'Sensors Offline',
		activities_completed_this_week_period: 'Activities Completed this week/period',
		activities_planned_for_next_week_period:
			'Activities Planned for next week/period',
		asset_monitoring: 'Asset Monitoring',
		recommended_actions: 'Recommended Actions',
		activities_in_progress: 'Activities in Progress',
		success_expansion_plans: 'Success Expansion Plans',
		recurring_issues_continuous_issue_discussion:
			'Recurring Issues/continuous issue discussion',
		roi_value_creation_summary: 'ROI/Value Creation Summary',
		questionnaire_form: 'Questionnaire Form',
		customer_product_feedback: 'Customer Product Feedback',
		save_send: 'save&send',
		completed_rois: 'Completed ROIs',
		roi_salvings_ca: 'ROI Salvings/CA',
		of_sensors: '# of Sensors',
		next_launch_date: 'Next Launch Date',
		created_at: 'Created at',
		export_to_pdf: 'Export to PDF',
		form_isnt_ready: "Form isn't ready",
		please_check_phone_number_form_field_first:
			'Please check phone number form field first',
		meeting_tracker_date: 'Meeting Tracker Date',
		name_is_missing: 'Name is missing',
		findings_issue_detection_action_plan: 'Findings/Issue Detection & Action Plan',
		roi_cost_avoidance: 'ROI/Cost Avoidance',
		pdm_data_screenshot: 'PDM Data Screenshot',
		history_roi_one_pager: 'History ROI One Pager',
		roi_ca_$: 'ROI/CA $',
		production_line_name: 'Production Line name',
		machine_name: 'Machine name',
		asset_name: 'Asset name',
		open_pdf_file: 'Open PDF file',
		do_you_really_want_to: 'Do you really want to',
		action_continue: 'action? Continue?',
		total_time: 'Total time',
		select_daterange_first: 'Select daterange first',
		high_alarm: 'High Alarm',
		low_alarm: 'Low Alarm',
		amplitude_alarm: 'Amplitude Alarm',
		possible_problems: 'Possible problems',
		setup_thresholds: 'Setup thresholds',
		view_file: 'View File',

		continue_and_update_alarm_threshold: 'Continue and Update Alarm Threshold',
		complete_save_and_update_alarm_threshold:
			'Complete/Save and Update Alarm Threshold',
		continue_or_save_changes: 'Continue or Save changes',
		unsaved_thresholds: 'Unsaved Thresholds',
		export_charts_to_pdf: 'Export charts to PDF',
		load_last_export: 'Load last export',
		sensors_should_be_selected: 'Sensors should be selected',
		save_progress: 'Save Progress',
		file_was_sent_on_your_email: 'File was sent on your email',
		should_be_lower_than: 'should be lower than',
		select_date_range_first: 'Select date range first',
		equipment_breakdown_maintenance_log: 'Equipment Breakdown/ Maintenance Log',
		see_parent_work_order: 'See Parent Work Order',
		start_work_order: 'Start Work Order',
		cost_savings: 'Cost Savings',
		running_total_materials: 'Running Total Materials',
		running_total_hours: 'Running Total Hours',

		enable_run_hour_tracking_for_sensors: 'Enable Run Hour Tracking for Sensors',
		show_run_hours: 'Show Run Hours',
		runtime_was_reset: 'Runtime was reset',
		run_hour_counter_reset: 'Run Hour Counter Reset',
		runtime_tracking_threshold_data_value: 'Runtime Tracking Threshold Data Value',
		converting_maintenance_request: 'Converting Maintenance Request',
		request_type: 'Request Type',
		request_fmax: 'Request Fmax',
		please_select_request_type_and_fmax: 'Please select request type and Fmax',
		fft_data_is_not_valid: 'FFT data is not valid',
		is_google_cloud_data: 'Is Google Cloud Data',
		cycles_counter: 'Cycles Counter',
		amount_cycles: 'Amount Cycles',
		should_be_selected: 'should be selected',
		reset_frequency_settings: 'Reset Frequency Settings',
		disable_iaq: 'Disable IAQ',
		command_should_be_filled: 'Command should be filled',
		time_waveform_full_bandwidth: 'Time Waveform Full Bandwidth',
		time_waveform_high_frequency_enveloping_hfe_peak_filtering:
			'Time Waveform High Frequency Enveloping (HFE) Peak Filtering',
		sending_fft_request_to_controller: 'Sending FFT request to controller',
		is_receive_sensors_anomaly: 'Is receive sensors anomaly',
		adding_notes: 'Adding Notes',
		number_of_graphs: 'Number of Graphs',
		reset_rotation: 'Reset Rotation',
		controller_received_the_request_properly:	'Controller received the request properly',
		banner_v2_subtype: 'Banner V2 Subtype',
		banner_v2_subtypes: 'Banner V2 Subtypes',
		show_archived: 'Show Archived',
		image_is_required: 'Image is required',
		
		devices_attached_to_it: 'devices attached to it',
		you_need_to_select_rpm_source_first: 'You need to select RPM source first',
		would_you_like_to_delete_it_anyway: 'Would you like to delete it anyway',
		please_type: 'Please type',
		to_confirm: 'to confirm',
		type_delete_here: 'Type "delete" here',
		please_type_delete_to_confirm: 'Please type "delete" to confirm',
		create_maintenance_log: 'Create Maintenance Log',
		script_version: 'Script Version',
		wrong_sensor_firmware_version: 'Wrong sensor firmware version',
		lube_version: 'Lube Version',
		all_values_must_be_a_number: 'All values must be a number',
		password_is_required: 'Password is required',
		forgot_password: 'Forgot Password',
		enter_your_password: 'Enter your password',
		send_code: 'Send code',
		check_code: 'Check code',
		resend_code: 'Resend code',
		enter_mfa_code: 'Enter MFA code',
		confirm_password: 'Confirm Password',
		phone_is_required: 'Phone is required',
		password_must: 'Password must',
		reports_saved_successfully: 'Reports saved successfully',
		start_report_manually: 'Start report manually',
		for_sensors_on_controller: 'For sensors on controller',
		multiple_fft: 'Multiple FFT',
		running_threshold: 'Running Threshold',
		joined_at: 'Joined at',
		shots_count_per_today: 'Shots count per today',
		total_shots_count: 'Total shots count',
		total_successful_shots_count: 'Total successful shots count',
		total_unsuccessful_shots_count: 'Total unsuccessful shots count',
		all_metrics: 'All Metrics',
		multi_view_charts: 'Multi-view Charts',
		is_report_by_notifiable_plants: 'Is report by notifiable plants',
		report_plants: 'Report Plants',
		notifications_for_all_monitoring_points: 'Notifications for all monitoring points',
		sending_lube_cycle_request: 'Sending lube cycle request',
		baseline_delta: 'Baseline Delta',
		warning_and_alarm_delta: 'Warning and Alarm Delta',
		thresholds_only: 'Thresholds Only',
		report_created: 'Report created',
		confirm_phone_number: 'Confirm Phone Number',
		fft_successfully_unlocked: 'FFT successfully unlocked',
		unlock_fft: 'Unlock FFT',
		flat_data_anomaly: 'Flat Data Anomaly',
		personal_favorite: 'Personal Favorite',
		company_favorite: 'Company Favorite',
		open_in_new_window: 'Open in new window',
		lube_based_device_address_id: 'Lube Based Device Address ID',
		lube_based_physical_sensor_id: 'Lube Based Physical Sensor ID',
		lube_trigger_metric_type: 'Lube Trigger Metric Type',
		re_trigger_samples: 'Re-trigger Samples',
	},

	aliases: {
		rpm_tooltip_prhrase: `Use {value} as the RPM speed value. <br/>
													Example: {value} * 60 + 500`,
    subtype_formula_tooltip: `Use {value} as the input from the IO)}. <br/>
													Example: {value} * 60 + 500 <br/>
													NB: The original formula will be applied before this formula`,
		password_validation: 'Password must be at least 8 characters long and contain at least one uppercase letter, one lowercase letter, one number, one special character and not be the same as your account name.',
		passwords_compar_error: 'Passwords do not match',
		mfa_auth_restriction: 'You cannot disable MFA for this account, as it is required by your organization\'s security policy.',
		reset_pass_msg: 'Link for reset password was sent on your email',
		mfa_code_send_msg: 'SMS with verification code was sent on your phone',
		verification_ok: 'Verification confirmed',
		pass_req_l_case: 'Have at least one lowercase character',
		pass_req_u_case: 'Have at least one Capital letter',
		pass_req_number: 'Have at least one number',
		pass_req_spec_char: 'Have at least one special character',
		pass_req_not_account_name: 'Not be the same as your account name',
		pass_req_length: 'Be at least 8 characters long',
		skip_mfa_check: 'Trust this device and dont ask MFA code next 7 days',
		mult_fft_confirm: 'Do you really want to request an FFT for all sensor on controller',
		mult_rebaseline_confirm: 'Do you really want to Rebaseline for sensor on controller',
		mfa_warn_1: 'Keep your account safe',
		mfa_warn_2: 'Two-Factor Authentication (2FA) will be required to login starting October 1st 2025 for all Plant Admin access users',
		mfa_warn_link: 'Set up 2FA today',
	  	prodline_warn_1: 'Please select at least one notifiable production line',
	  	creation_link_exp: 'The Password Creation Link has expired. Please enter your email below and click send. <b>A new link will then be sent to your inbox momentarily</b>',
	  	to_clipboard_msg: 'Link was copied to the clipboard',
	  	mfa_warn_3: 'If You want to change Phone Number - Please disable MFA or change it to Authenticator',
	  	anomaly1: 'Flat metric data anomaly',
	  	api_secret_warn: 'Is the only time You will be able to see the secret',
	  	frequency_reset: 'Frequency settings successfully reset before saving because the lube method changed. Set new frequency settings and save.',
	  	del_sensor: 'You’re removing the sensor from the item card',
	  	dt_cost_req_togr: 'Downtime Hour and Hours Saved must be filled together',
	},

	constants: {
		'super_admin': 'Super Admin',
		'plant_user': 'Plant User',
		'distributor': 'Distributor',
		'plant_admin': 'Plant Admin',
		'plant_superintendent': 'Plant Superintendent',
		'oee_proccess': 'OEE Proccess',
		'corporate': 'Corporate',
		'metric': 'Metric',
		'imperial': 'Imperial',
		'pending': 'Pending',
		'approved': 'Approved',
		'completed': 'Completed',
		'success': 'Success',
		'fail': 'Fail',
		unverified: 'Unverified',

		'humidity': 'Humidity',
		'temperature': 'Temperature',

		'warning': 'Warning',
		'alarm': 'Alarm',
		'mixed': 'Mixed',
		'lube': 'Lube',
		'good': 'Good',
		'normal': 'Normal',
		'lubeline': 'Lubeline',

		// -------------new-------------
		'high_zone': 'High zone',
		'low_zone': 'Low zone',
		'high_alarm_zone': 'High alarm zone',
		'low_alarm_zone': 'Low alram zone',
		'off_alarm': 'Off alarm',
		'alarm_zone': 'Alarm zone',
		'warning_zone': 'Warning zone',
		'lubeline_zone': 'Lubeline zone',
		'baseline_zone': 'Baseline zone',
		'off_alarm_zone': 'Off Alarm zone',

		'motor': 'Motor',

		'jan': 'Jan',
		'feb': 'Feb',
		'mar': 'Mar',
		'apr': 'Apr',
		'may': 'May',
		'jun': 'June',
		'jul': 'July',
		'aug': 'Aug',
		'sept': 'Sept',
		'oct': 'Oct',
		'nov': 'Nov',
		'dec': 'Dec',

		'january': 'January',
		'february': 'February',
		'march': 'March',
		'april': 'April',
		'may_f': 'May',
		'june': 'June',
		'july': 'July',
		'august': 'August',
		'september': 'September',
		'october': 'October',
		'november': 'November',
		'december': 'December',

		'monday': 'Monday',
		'tuesday': 'Tuesday',
		'wednesday': 'Wednesday',
		'thursday': 'Thursday',
		'friday': 'Friday',
		'satday': 'Saturday',
		'sunday': 'Sunday',

		// -----------New----------
		'acute': 'Acute',
		'chronic': 'Chronic',
		'current': 'Current',
		'db_level': 'dB Level',
		'pressure': 'Pressure',
		'rpm': 'RPM',
		'motor_amperage': 'Motor Amperage',
		'x_acceleration': '(X) Acceleration',
		'y_acceleration': '(Y) Acceleration',
		'z_acceleration': '(Z) Acceleration',
		'x_velocity': '(X) Velocity',
		'y_velocity': '(Y) Velocity',
		'z_velocity': '(Z) Velocity',
		'mm_sec': 'mm/sec',
		'x_displacement': '(X) Displacement',
		'y_displacement': '(Y) Displacement',
		'z_displacement': '(Z) Displacement',
		'external_temperature': 'External Temperature',
		'indoor_air_quality': 'Indoor Air Quality',
		'axial_velocity': 'Axial Velocity',
		'axial_acceleration': 'Axial Acceleration',
		'radial_v_velocity': 'Radial (V) Velocity',
		'radial_v_acceleration': 'Radial (V) Acceleration',
		'radial_h_velocity': 'Radial (H) Velocity',
		'radial_h_acceleration': 'Radial (H) Acceleration',
		'mm_per_second': 'mm/s',
		'inches_per_second': 'in/s',
		'celsius': 'Celsius',
		'fahrenheit': 'Fahrenheit',
		'g': 'g',
		'hertz': 'Hz',
		'dbuv': 'dB&micro;V',
		'amps': 'Amps',
		'percent': '%',
		'psi': 'PSI',
		'iaq': 'IAQ',
		'mm': 'mm',
		'inches': 'inches',
		'rebaseline': 'Rebaseline',
		'corrective_action': 'Corrective Action',
		'change_item': 'Change Item',
		'1_day': '1 Day',
		'7_days': '7 Days',
		'month': 'Month',
		'custom_range': 'Custom range',
		'banner': 'Banner',
		'ultrasound': 'Ultrasound',
		'ultrasound_white_river': 'Ultrasound White River',
		'banner_counter': 'Banner Counter',
		'ncd': 'NCD',
		'colortech_vfd_pressure_rpm_amps': 'Colortech VFD Pressure RPM/AMPs',
		'pulsar': 'Pulsar',
		'perma': 'Perma',
		'battery': 'Battery',
		'line_powered': 'Line Powered',
		'graph': 'Graph',
		'dxm': 'DXM',
		'acknowledge_rebaseline': 'Acknowledge rebaseline',
		'controller': 'Controller',
		'sensor_update_rebaseline': 'Rebaseline',
		'purchase_request': 'Purchase Request',
		'service_request': 'Service Request',
		'same_value': 'Same Value',
		'range': 'Range',
		'numeric': 'Numeric',
		'percent_str': 'Percent',
		'in_work': 'In Work',
		'closed': 'Closed',
		'health_safety': 'Health Safety',
		'production_loss': 'Production Loss',
		'cost_reduction': 'Cost Reduction',
		'future_opportunity': 'Future Opportunity',
		'refurbishment': 'Refurbishment',
		'fabrication': 'Fabrication',
		'repair': 'Repair',
		'weekly': 'Weekly',
		'monthly': 'Monthly',
		'yearly': 'Yearly',
		'period_type': 'Period Type',
		'period_dates': 'Period Dates',
		'overdue': 'Overdue',
		'today': 'Today',
		'this_week': 'This Week',
		'this_month': 'This month',
		'manual': 'Manual',
		'automatic': 'Automatic',
		'item': 'Item',
		'nameplate': 'Nameplate',
		'plant': 'Plant',
		'master': 'Master',
		'auto': 'Auto',
		'work_break': 'Work break',
		'deviation': 'Deviation',
		'further_below_run_rate': 'Further Below Run Rate',
		'cell_modem': 'Cell Modem',
		'customer_connection': 'Customer Connection',
		'base': 'Base',
		'advanced': 'Advanced',
		'mail': 'Mail',
		'sms': 'SMS',
		'on_hold': 'On Hold',
		'denied': 'Denied',
		'all_in_one': 'All in one',
		'cm1l': 'CM1L',
		'decibells': 'Decibells',
		'extra_vibration': 'Extra Vibration',
		'custom_pdm_setup': 'Custom PDM Setup',
		'all_in_one_temp_vibe': 'All in one Temp/Vibe',
		'wired_temp_vibe': 'Wired Temp/Vibe',
		'temp_vibe_current': 'Temp/Vibe/Current',
		'environmental': 'Environmental',
		'cm1l_sensor_custom_a': 'CM1L Sensor Custom A',
		'ue_sensor': 'UE Sensor',
		'sdt_sensor_0_10v': 'SDT Sensor 0-10V',
		'sdt_sensor_4_20ma': 'SDT Sensor 4-20mA',
		'sdt_sensor_full_spectrum': 'SDT Sensor Full Spectrum',
		'temperature_vibration': 'Temperature Vibration',
		'ncd_sdt_full_spectrum_ultrasound': 'NCD - SDT Full Spectrum Ultrasound',
		'minute': 'Minute',
		'hour': 'Hour',
		'day': 'Day',
		'lubricated': 'Lubricated',
		'empty': 'Empty',
		'block': 'Block',
		'blocked': 'Blocked',
		'glitched': 'Glitched',
		'lubricator_error': 'Lubricator Error',
		'lubricator_cartridge_empty': 'Lubricator Cartridge Empty',
		'lubricator_blocked': 'Lubricator Blocked',
		'lube_ok': 'Lube OK',
		'loss_connection': 'Loss Connection',
		'some_glitch': 'Some Glitch',
		'unknown_status': 'Unknown Status',
		'gain_increase': 'Gain +',
		'gain_decrease': 'Gain -',
		'reset': 'Reset',
		'proccess': 'Proccess',
		'yesterday': 'Yesterday',
		'last_7_days': 'Last 7 days',
		'last_30_days': 'Last 30 days',
		'last_60_days': 'Last 60 days',
		'last_90_days': 'Last 90 days',
		'last_month': 'Last month',
		'last_1_hour': 'Last 1 hour',
		'last_3_hours': 'Last 3 hours',
		'last_12_hours': 'Last 12 hours',
		'ultrasound_sdt': 'Ultrasound (SDT)',
		'usound': 'USound',
		'ultrasound_sdt_4_20': 'Ultrasound (SDT 4-20)',
		'humidity_temperature': 'Humidity, Temperature',
		'hum_temp': 'Hum/Temp',
		'vibe_temp': 'Vibe/Temp',
		'temp_vibe': 'Temp/Vibe',
		'vibration_temperature_current': 'Vibration, Temperature, Current',
		'vibration_temperature': 'Vibration, Temperature',
		'vibe_temp_curr': 'Vibe/Temp/Curr',
		'custom_pdm': 'Custom PDM',
		'custom': 'Custom',
		'lubematrix': 'LubeMatrix',
		'lubematrix_sdt': 'LubeMatrix (SDT)',
		'lubematrix_sdt_4_20': 'LubeMatrix (SDT 4-20)',
		'lubematrix_sdt_full_spectrum': 'LubeMatrix (SDT Full Spectrum)',
		'wired_vibration_temperature': 'Wired Vibration, Temperature',
		'ultrasound_sdt_full_spectrum': 'Ultrasound (SDT Full Spectrum)',
		'humidity_temperature_air_quality': 'Humidity, Temperature, Air Quality',
		'inches_sec': 'inches/sec',

		// --------------
		'ncd_pressure': 'NCD Pressure',
		'all_in_one_aa_battery': 'All-In-One - AA Battery',
		'all_in_one_c_battery': 'All-In-One - C Battery',
		'wired_aa_battery': 'Wired - AA Battery',
		'wired_d_battery': 'Wired - D Battery',
		'wired_stainless_steel_aa_battery': 'Wired Stainless Steel - AA Battery',
		'wired_stainless_steel_d_battery': 'Wired Stainless Steel - D Battery',
		'time_waveform_x': 'Time Waveform (X)',
		'time_waveform_y': 'Time Waveform (Y)',
		'time_waveform_z': 'Time Waveform (Z)',
		'transformed_acceleration_x': 'Transformed Acceleration (X)',
		'transformed_acceleration_y': 'Transformed Acceleration (Y)',
		'transformed_acceleration_z': 'Transformed Acceleration (Z)',
		'raw_acceleration_x': 'Raw Acceleration (X)',
		'raw_acceleration_y': 'Raw Acceleration (Y)',
		'raw_acceleration_z': 'Raw Acceleration (Z)',
		'velocity_x': 'Velocity (X)',
		'velocity_y': 'Velocity (Y)',
		'velocity_z': 'Velocity (Z)',
		'cpm': 'CPM',

		'year_to_date': 'Year to Date',
		'first_quarter': 'First Quarter',
		'second_quarter': 'Second Quarter',
		'third_quarter': 'Third Quarter',
		'fourth_quarter': 'Fourth Quarter',
		last_1_month: 'Last 1 Month',
		last_6_months: 'Last 6 Months',
		last_12_months: 'Last 12 Months',

		'psig_0_50': 'PSIG 0-50',
		'psig_0_150': 'PSIG 0-150',
		'psis_0_500': 'PSIS 0-500',
		'psis_0_3000': 'PSIS 0-3000',
		'banner_temp_vibe_v2': 'Banner Temp Vibe V2',
		'time_domain_high_pass_buffer': 'Time Domain High Pass Buffer',
		'time_domain_high_frequency_enveloped': 'Time Domain High Frequency Enveloped',
		'time_domain_low_pass_buffer': 'Time Domain Low Pass Buffer',
		'time_domain_full_band_buffer': 'Time Domain Full Band Buffer',
		'offline': 'Offline',
		'lube_matrix_sdt_temp_c': 'Lube Matrix SDT Temp C',
		'lube_matrix_sdt_temp_f': 'Lube Matrix SDT Temp F',
		'ncd_custom_4_20': 'NCD Custom 4-20',
		'banner_v2_generic': 'Banner V2 Generic',
		'banner_temp_vibe_v2_1': 'Banner Temp Vibe V2.1',
		'position_1': '1 Position',
		'position_2': '2 Positions',
		'warning_alarm': 'Warning/Alarm',
		'low_high_alarms': 'Low/High Alarms',
		'rsp_timeout': 'RSP Timeout',
		'amplitude_alarm': 'Amplitude Alarm',
		'controller_offline': 'Controller Offline',
		'sensor_anomaly': 'Sensor Anomaly',
		'graph_note': 'Graph Note',

		'acute_warning': 'Acute Warning',
		'acute_alarm': 'Acute Alarm',
		'chronic_warning': 'Chronic Warning',
		'chronic_alarm': 'Chronic Alarm',
		'temperature_warning': 'Temperature Warning',
		'temperature_alarm': 'Temperature Alarm',
		'lube_alarm': 'Lube Alarm',
		'low_alarm': 'Low Alarm',
		'high_alarm': 'High Alarm',
		'other_warning': 'Other Warning',
		'other_alarm': 'Other Alarm',
		'sensor_offline': 'Sensor Offline',
		'battery_status': 'Battery Status',
		'fft_alerts': 'FFT Alerts',
		'sensor_suspect_data': 'Sensor Suspect Data',
		'lube_matrix_alerts': 'Lube Matrix Alerts',
		'oee_alerts': 'OEE Alerts',
		'purpose': 'Purpose',
		'sensor_only': 'Sensor only',
		'z_peak_acceleration': 'Z Peak Acceleration',
		'z_crest_factor': 'Z Crest Factor',
		'z_curtosis': 'Z Curtosis',
		'z_rms_velocity': 'Z-Axis RMS Velocity',
		'y_rms_velocity': 'Y-Axis RMS Velocity',
		'x_rms_velocity': 'X-Axis RMS Velocity',
		'hi_frequency_rms_acceleration_magnitude': 'High-Frequency RMS Acceleration Magnitude',
		'hi_frequency_rms_acceleration': 'High-Frequency RMS Acceleration',
		'z_hi_frequency_rms_acceleration': 'Z-Axis High-Frequency RMS Acceleration',
		'y_hi_frequency_rms_acceleration': 'Y-Axis High-Frequency RMS Acceleration',
		'x_hi_frequency_rms_acceleration': 'X-Axis High-Frequency RMS Acceleration',
		'max_peak_frequency': 'Max Peak Frequency',
		'max_peak_frequency_2nd': 'Max Peak Frequency 2nd',

		magnitude_xyz_hi_frequency_rms_acceleration: 'Magnitude (XYZ) High-Frequency RMS Acceleration',
		magnitude_xyz_hi_frequency_pk_acceleration: 'Magnitude (XYZ) High-Frequency Pk Acceleration',
		magnitude_xyz_hi_frequency_crest_factor: 'Magnitude (XYZ) High-Frequency Crest Factor',
		magnitude_xyz_hi_frequency_kurtosis: 'Magnitude (XYZ) High-Frequency Kurtosis',

		rms_velocity: 'RMS Velocity',
		x_rms_velocity_mm: 'X-Axis RMS Velocity',
		y_rms_velocity_mm: 'Y-Axis RMS Velocity',
		z_rms_velocity_mm: 'Z-Axis RMS Velocity',

		magnitude_xyz_full_band_rms_acceleration: 'Magnitude (XYZ) Full Band RMS Acceleration',
		magnitude_xyz_full_band_pk_pk_acceleration: 'Magnitude (XYZ) Full Band Pk-to-Pk Acceleration',
		max_peak_frequency_from_3_axis: 'Max Peak Frequency from 3 Axis',
		x_axis_peak_velocity_component_frequency: 'X-Axis Peak Velocity Component Frequency',
		y_axis_peak_velocity_component_frequency: 'Y-Axis Peak Velocity Component Frequency',
		z_axis_peak_velocity_component_frequency: 'Z-Axis Peak Velocity Component Frequency',

		x_axis_high_frequency_rms_acceleration: 'X-Axis High-Frequency RMS Acceleration',
		y_axis_high_frequency_rms_acceleration: 'Y-Axis High-Frequency RMS Acceleration',
		z_axis_high_frequency_rms_acceleration: 'Z-Axis High-Frequency RMS Acceleration',

		x_axis_pk_acceleration: 'X-Axis Pk Acceleration',
		y_axis_pk_acceleration: 'Y-Axis Pk Acceleration',
		z_axis_pk_acceleration: 'Z-Axis Pk Acceleration',

		x_axis_crest_factor: 'X-Axis Crest Factor',
		y_axis_crest_factor: 'Y-Axis Crest Factor',
		z_axis_crest_factor: 'Z-Axis Crest Factor',

		x_axis_kurtosis: 'X-Axis Kurtosis',
		y_axis_kurtosis: 'Y-Axis Kurtosis',
		z_axis_kurtosis: 'Z-Axis Kurtosis',

		x_axis_full_band_rms_acceleration_g: 'X-Axis Full Band RMS Acceleration',
		y_axis_full_band_rms_acceleration_g: 'Y-Axis Full Band RMS Acceleration',
		z_axis_full_band_rms_acceleration_g: 'Z-Axis Full Band RMS Acceleration',

		x_axis_full_band_pk_pk_acceleration_g: 'X-Axis Full Band Pk-to-Pk Acceleration',
		y_axis_full_band_pk_pk_acceleration_g: 'Y-Axis Full Band Pk-to-Pk Acceleration',
		z_axis_full_band_pk_pk_acceleration_g: 'Z-Axis Full Band Pk-to-Pk Acceleration',

		x_axis_peak_acceleration_frequency_component: 'X-Axis Peak Acceleration Frequency Component',
		y_axis_peak_acceleration_frequency_component: 'Y-Axis Peak Acceleration Frequency Component',
		z_axis_peak_acceleration_frequency_component: 'Z-Axis Peak Acceleration Frequency Component',

		hi_frequency_pk_acceleration: 'High-Frequency Pk Acceleration',
		hi_frequency_crest_factor: 'High-Frequency Crest Factor',
		hi_frequency_kurtosis: 'High-Frequency Kurtosis',
		hi_frequency_full_band_rms_acceleration: 'Full Band RMS Acceleration',
		hi_frequency_full_band_pk_pk_acceleration: 'Full Band Pk-to-Pk Acceleration',
		hi_frequency_peak_acceleration_frequency_component: 'High-Frequency Peak Acceleration Frequency Component',
		full_band_peak_acceleration_frequency_component: 'Full Band Peak Acceleration Frequency Component',
		external_input_rpm: 'External Input RPM',
		external_input: 'External Input',
		linespeed_rpm: 'Linespeed RPM',
		specification_rpm: 'Specification RPM',
		manual_rpm: 'Manual RPM',
		lube_v3: 'Lube V3',
		in_progress: 'In Progress',
		undefined: 'Undefined',
		unit: 'Unit',
		time_delta: 'Time Delta',
		ultrasound_high_frequency_impact_index: 'Ultrasound/High-Frequency Impact Index',
		ultrasound_high_frequency_peak: 'Ultrasound/High-Frequency Peak',
		crest_factor: 'Crest Factor',
		kurtosis: 'Kurtosis',
		ultrasound_rms: 'Ultrasound RMS',
		ultrasound_impact: 'Ultrasound Impact',
		ultrasound_peak: 'Ultrasound Peak',
		ultrasound_crest_factor: 'Crest Factor',
		ultrasound_curtosis: 'Kurtosis',
		high_frequency_rms_acceleration: 'High Frequency RMS Acceleration',
		hfe_impact_index: 'HFE Impact Index',
		high_frequency_pk_acceleration: 'High Frequency Pk Acceleration',
		high_frequency_crest_factor: 'High Frequency Crest Factor',
		high_frequency_kurtosis: 'High Frequency Kurtosis',
		full_band_rms_acceleration: 'Full Band RMS Acceleration',
		full_band_peak_acceleration_frequency: 'Full Band Peak Acceleration Frequency',
		full_band_crest_factor: 'Full Band Crest Factor',
		full_band_kurtosis: 'Full Band Kurtosis',
		peak_velocity_frequency_component: 'Peak Velocity Frequency Component',
		ultrasound_impact_index: 'Ultrasound Impact Index',
		banner_m25: 'Banner M25',
		no_start_lubrication_command_response: 'No Start Lubrication Command Response',
		no_lubrication_status_response: 'No Lubrication Status Response',
		controller_timeout: 'Controller Timeout',
		controller_error: 'Controller Error',
		unsuccessful_shot: 'Unsuccessful Shot',
		cycle_did_not_affect: 'Cycle did not affect',
		shots_full_spent: 'Shots full spent',
		lubrication_unlocked: 'Lubrication unlocked',
		compare: 'Compare',
		standard_warning_alarm: 'Warning/Alarm',
		standard_low_high: 'Low/High',
		unlocked: 'Unlocked',
		no_fft_response: 'No FFT Response',
		node_offline: 'Node Offline',
		unconfirmed_fft_request: 'Unconfirmed FFT Request',
		usg: 'USg',
	},

	short_name: {
		hi_freq_rms_accel: 'High Freq RMS Accel',
		ext_temp: 'Ext Temp',
		iaq: 'IAQ',
		hi_freq_accel: 'Hi Freq Accel',
		hi_freq_pk_accel: 'Hi Freq Pk Accel',
		hi_freq_crest_factor: 'Hi Freq Crest Factor',
		hi_freq_kurtosis: 'Hi Freq Kurtosis',
		full_band_accel: 'Full Band Accel',
		full_band_pk_pk_accel: 'Full Band Pk-Pk Accel',
		x_rms_velocity: 'X RMS Velocity',
		y_rms_velocity: 'Y RMS Velocity',
		z_rms_velocity: 'Z RMS Velocity',
		peak_freq_3_axis: 'Peak Freq 3 Axis',
		x_peak_vel_comp_freq: 'X Peak Vel Comp Freq',
		y_peak_vel_comp_freq: 'Y Peak Vel Comp Freq',
		z_peak_vel_comp_freq: 'Z Peak Vel Comp Freq',
		x_hi_freq_rms_accel: 'X Hi Freq RMS Accel',
		y_hi_freq_rms_accel: 'Y Hi Freq RMS Accel',
		z_hi_freq_rms_accel: 'Z Hi Freq RMS Accel',
		x_pk_accel: 'X Pk Accel',
		y_pk_accel: 'Y Pk Accel',
		z_pk_accel: 'Z Pk Accel',
		x_crest_factor: 'X Crest Factor',
		y_crest_factor: 'Y Crest Factor',
		z_crest_factor: 'Z Crest Factor',
		x_kurtosis: 'X Kurtosis',
		y_kurtosis: 'Y Kurtosis',
		z_kurtosis: 'Z Kurtosis',
		x_full_band_rms_accel: 'X Full Band RMS Accel',
		y_full_band_rms_accel: 'Y Full Band RMS Accel',
		z_full_band_rms_accel: 'Z Full Band RMS Accel',
		x_full_band_pk_pk_accel: 'X Full Band Pk-Pk Accel',
		y_full_band_pk_pk_accel: 'Y Full Band Pk-Pk Accel',
		z_full_band_pk_pk_accel: 'Z Full Band Pk-Pk Accel',
		x_peak_accel_comp_freq: 'X Peak Accel Comp Freq',
		y_peak_accel_comp_freq: 'Y Peak Accel Comp Freq',
		z_peak_accel_comp_freq: 'Z Peak Accel Comp Freq',
		full_band_pk_accel_freq: 'Full Band Pk Accel Freq',
		peak_vel_comp_freq: 'Peak Vel Comp Freq',
	},
	
	technology: {
		vibration_temperature: 'Vibration, Temperature',
		vibration_temperature_current: 'Vibration, Temperature, Current',
		ultrasound: 'Ultrasound',
		humidity_temperature: 'Humidity, Temperature',
		custom: 'Custom',
		lube_matrix: 'LubeMatrix',
		humidity_temperature_air_quality: 'Humidity, Temperature, Air Quality',
		pressure: 'Pressure',
		ultrasound_vibration_temperature: 'Ultrasound, Vibration, Temperature',
		uvt: 'UVT',
	}
};
